### ISSUE TITLE
HMIP Broll

### ISSUE THREAD

**Issue by theguitar666** [marcsowen/homebridge-homematicip#13]
Thanks for the great work, Plug-in works fine so far. I saw that HMIP Broll should be already supported, nevertheless  I get the following message:

Device not implemented: HmIP-BROLL - Küche 1 via type BRAND_SHUTTER

Any hint?

**Comment by toni-Berg** [comment]
Hello, the HMIP-BROLL doesn't work for me either. 
The following is displayed in the log.  Device not implemented: HMIP-BROLL. 
Please also implement the HmIP-BBL. 
Thank you for the good work.

**Comment by marcsowen** [comment]
Oops... I accidentally forgot to include HmIP-BROLL. Should work with 0.0.12 now. HmIP-BBL and HmIP-FBL will follow soon.

**Comment by theguitar666** [comment]
Thanks, it works now!
