### ISSUE TITLE
HomematicIP response is incomplete or could not be parsed: false

### ISSUE THREAD

**Issue by Marioishappy** [marcsowen/homebridge-homematicip#15]
Hello, first of all Thanks very much for your help and creation of such solutions.

I am running Homebridge 1.1.6 on an Raspberry Pi 1 
the Homematic Access Point is connected via LAN as the Raspberry.

now i´ve put in my Data with Dashes  - and with < > and without , but there is always the message

HomematicIP response is incomplete or could not be parsed: false

what am I doing wrong?

the API Token is the Key writen on the box above the ID !?
or do i have to get an other programm to find it out ?

and what is the right way of set the Data in?

{
    "platform": "HomematicIP",
    "name": "HomematicIP",
    "access_point": "<your access point ID>",
    "auth_token": "<your API auth token>"
}

{
    "platform": "HomematicIP",
    "name": "HomematicIP",
    "access_point": "<3014-F711-A001-03DA-4993-CT03>",
    "auth_token": "<3WYQ7-CKB2L-5QNN2-XB3E1-CL46CT>"
}

{
    "platform": "HomematicIP",
    "name": "HomematicIP",
    "access_point": "3014-F711-A001-03DA-4993-CT03",
    "auth_token": "3WYQ7-CKB2L-5QNN2-XB3E1-CL46CT"
}

{
    "platform": "HomematicIP",
    "name": "HomematicIP",
    "access_point": "<3014F711A00103DA4993CT03",
    "auth_token": "<3WYQ7CKB2L5QNN2XB3E1CL46CT"
}

Thanks very much and Best Regards

**Comment by marcsowen** [comment]
The "auth_token" is a key which is generated just for a single application, in this case homebridge-homematicip. It's not written on any label. You need to generate it yourself by setting the "access_point" parameter like you did:
```
{
  "platform": "HomematicIP",
  "name": "HomematicIP",
  "access_point": "3014F711A00103DA4993CT03"
}
```
After that, restart Homebridge. You will be asked to press the blue, glowing button on your access point. After a few seconds you will see your personal auth_token in the home bridge logs. Edit your homebridge config again:
```
{
  "platform": "HomematicIP",
  "name": "HomematicIP",
  "access_point": "3014F711A00103DA4993CT03"
  "auth_token": "THE_CODE_YOU_JUST_SAW_IN_THE_LOGS"
}
```
Be aware that this doesn't currently work with a PIN set in your HomematicIP App. Remove the PIN in the app first and retrieve your auth_token as described above. After that you can re-enable the PIN again.

**Comment by Hitmn1** [comment]
Hello,

my HomematicIP Access Point starts with "3015". Relabelt by Silvercrest (LIDL).

`{
            "platform": "HomematicIP",
            "name": "HomematicIP",
            "access_point": "3015............"
        }`

After restart Hombrige an error occure.

`[1/22/2021, 3:44:27 PM] [HomematicIP] Cannot request: url=https://srv03.hmip-oem0840.com:6969/hmip/auth/connectionRequest, request="{\"deviceId\":\"34fca11a-6d73-4f33-a5c5-a05ce0b73bb2\",\"deviceName\":\"homebridge-homematicip\",\"sgtin\":\"30150.....\"}", headers={"content-type":"application/json","accept":"application/json","VERSION":"12","CLIENTAUTH":"F904FEC8CB2591D9D7387D47F39B19462DB007E3EB16D04072FD6873B59E93E0D9380DC432B2204E708A0FBC90113617BDB01CEB2C1DFB3E6F6DE20420B6B2B0"}, code=400, message=Bad Request
[1/22/2021, 3:44:27 PM] [HomematicIP] Cannot start auth request for access_point=3015........`

Is there a difference between the original HomematicIP AP and the Silvercrest label?

**Comment by marcsowen** [comment]
Unfortunately I don't have a Silvercrest device available for test. It seems to contact a different server "oem0840", but the protocol seems to be identical.

Do you have a PIN set in the app? If yes, try version 0.0.14 and try again with the config property "pin" set to the pin you set up in the app. If you don't have a pin, remove the config property.

**Comment by Marioishappy** [comment]
Hello Marc, just want to say many thanks , your Description was very helpful and worked out.
How can I donate your plug-in ? 
beat regards Mario

**Comment by Hitmn1** [comment]
> Do you have a PIN set in the app? If yes, try the latest version.

Thank you, this was the fault.

**Comment by marcsowen** [comment]
@Marioishappy Good to hear. Thanks for the offer. Currently I'm happy when people are using and contributing to the project by testing and posting issues. But I'll think about it. :)

@Hitmn1 Perfect! I close the issue then.
