### ISSUE TITLE
Homematic radiator temperatureOffset should be considered in the HeatingCoolingState functions

### ISSUE THREAD

**Issue by MaxiKingXXL** [marcsowen/homebridge-homematicip#17]
When you enter an offset in Homematic IP for the radiators it should be considered in valveActualTemperature or/and Heating/Cooling status calculation.

**Comment by marcsowen** [comment]
Can you explain it a bit more. I don't use temperature offset, but I tried it with my HmIP-WTH2 thermostat. When I set a temperature offset, the actual temperature reported by the device is already the sum of the real current temperature and the offset. So when the thermostat reports a real temperature of 21 degrees before and I set up an offset of 1 degree, the current temperature will show 22 degrees.

Is the behavior different with the heating thermostat devices connected to the radiators?

**Comment by MaxiKingXXL** [comment]
I use the offset just for a HmIP-eTRV-B without a Wall Thermostat. When I set the room temperature to 21°C on the device or in the Homematic app I  get a controlled room real temperature of 22.5 °C in the room. For any reason it's always 1.5°C to high.
Because of this I added the offset of 1.5 for this device. With the offset I get a real room temperature controlled by the radiator as configured of 21°C. The device setting and real room temperature are in sync now. As a user I don't have to worry about the offset anymore. In Homematic it's working fine now.

In Homebridge the adjusted temperature shows up as (real + offset = 22.5 °C) which the device seems to use for room temperature control. As a user that's confusing because the user might not know the offset.

I think it might be better to show the  valveActualTemperature - temperatureOffset as current room temperature in Homebridge which should be the real room temperature.

**Comment by marcsowen** [comment]
I understand your problem, but I'm still not convinced it's done right. What current temperature is the thermostat showing on the display? Isn't it also 22.5 degrees? And shouldn't the number on the display of the thermostat be in sync with the number in the Home app? It's a bit confusing... I better think about it tomorrow.

**Comment by MaxiKingXXL** [comment]
At least the Radiator Thermostat - basic and the App shows only the configured temperature which is 21°C if you don't have a Wall Thermostat added to the room. In Homematic I can't see the current room temperature. 

I aggree that usually there should be no correction needed. From my perspectice it's a design issue in Homematice that they provide the measured temperature + offset as valveActualTemperature.  But I woudn't expect that they fix it.

Maybe it could an optional parameter of the plugin which enabled this additional correction.
