### ISSUE TITLE
Implementing HmIP-BWTH and HmIP-STHO-A

### ISSUE THREAD

**Issue by modi80** [marcsowen/homebridge-homematicip#19]
it would be great if you could implement HmIP-BWTH and HmIP-STHO-A in the homebridge-homematicip plugin for hoobs.

https://github.com/coreGreenberet/homematicip-rest-api/issues/114#issuecomment-767381606

**Comment by marcsowen** [comment]
I will look into it. It probably takes a couple of days...

**Comment by modi80** [comment]
sounds great, thank you for your help

**Comment by marcsowen** [comment]
Have a look at version >=0.0.19. It's completely untested so please test and let me know if something isn't working right.

**Comment by modi80** [comment]
Just updated to 0.0.20 and it seems that everything's working great (correct temperature, immediate reaction of a homekit temperature change in homematic).
The .5 scaling of the current temperature is because of homekit, right?
Thank you for the fast integration!

**Comment by marcsowen** [comment]
Yes, unfortunately the Home-App displays temperatures with a resolution of 0.5 degrees. That's probably because 0.5 degrees is more than enough when used with Fahrenheit in the US. All I can say is that homebridge-homematicip transmits the full resolution to HomeKit. I believe the Eve-App shows a higher resolution.

**Comment by modi80** [comment]
Hey, I noticed a problem with the outside temperature below 0° Celsius. In that case the HmIP-STHO-A is shown as "no response", air humidity is still working.

**Comment by marcsowen** [comment]
This is a weird HomeKit "bug" where the minimum temperature of the current temperature is 0 degrees Celsius. I hopefully fixed it in 0.1.1.

**Comment by modi80** [comment]
Wow, that was fast :) Yes, it's fixed now. Thank you!

**Comment by modi80** [comment]
Just noticed that there is also a minus in front of the "0,0", when there is an outside temperature in the Homematic App of "-0,1".

**Comment by marcsowen** [comment]
I don't quite understand. HomematicIP-App shows "-0,1" and the Home App shows "-0,0"?

**Comment by modi80** [comment]
Yes, Home App shows "-0,0", but this should be "0,0". Beginning with "-0,5" and lower the minus is correct.
