### ISSUE TITLE
Implementing HmIP-SWD

### ISSUE THREAD

**Issue by lurid-bogey** [marcsowen/homebridge-homematicip#20]
First, thanks a lot for the great job you’re doing!

Second, I’d like to ask if there is any chance implementing the HmIP-SWD Water Sensor. (Or maybe it is already implemented?)

**Comment by marcsowen** [comment]
Thanks! I put it on the list.

**Comment by marcsowen** [comment]
It should be included in version >=0.1.1. (0.1.0 had a nasty bug I hopefully fixed.)

**Comment by lurid-bogey** [comment]
Thank you. The sensors are working now.
