### ISSUE TITLE
Implementing  HmIP-WTH-B   (Homematic IP Wall Thermostat – basic)

### ISSUE THREAD

**Issue by MaxiKingXXL** [marcsowen/homebridge-homematicip#21]
Can you add the device "Homematic IP Wall Thermostat – basic"  HmIP-WTH-B please?

[HomematicIP] Device not implemented: HmIP-WTH-B - ... via type WALL_MOUNTED_THERMOSTAT_BASIC_HUMIDITY

Thanks

**Comment by marcsowen** [comment]
Try version >=0.0.19 and let me know if something isn't working right. :)

**Comment by MaxiKingXXL** [comment]
Thanks for adding the device!

The temperature and humidity shows up in the Homebridge device view now.
The temperature shows up properly in the Home app. But for any reason the humidity is not showing up as a separate box/sensor. It's only visible in the settings of the device. Is this the correct behave or shouldn't the humidity show up as a separate sensor?

**Comment by marcsowen** [comment]
Yes, unfortunately that's a design decision by Apple in the Home-App. The Eve-App displays the humidity more prominently.
