### ISSUE TITLE
Support for HmIP-eTRV-E

### ISSUE THREAD

**Issue by mike4president** [marcsowen/homebridge-homematicip#218]
Hi,

is the new Homematic IP Eve Radiator going to be supported? 

https://homematic-ip.com/de/produkt/heizkoerperthermostat-evo

Thanks

**Comment by SvenLie** [comment]
Hi,

currently is this product not supported by the used rest api wrapper (https://github.com/coreGreenberet/homematicip-rest-api). If it is available, we can add the support i think

**Comment by mike4president** [comment]
Unfortunately the used rest api wrapper (https://github.com/coreGreenberet/homematicip-rest-api) is discontinued so it will probably never be supported 😒

**Comment by SvenLie** [comment]
I could try to add it to work like the other eTRV-Radiators. I will open a merge request, so we can try that.

**Comment by mike4president** [comment]
Thanks, that would be great

**Comment by SvenLie** [comment]
You should see a warning like below in your homebridge

`Device not implemented: ${device.modelType} - ${device.label} via type ${device.type}`

Could you tell me the device.type part please? So I can confirm, that i researched the correct one.
