### ISSUE TITLE
Homematic Alarm 

### ISSUE THREAD

**Issue by Killtroy** [marcsowen/homebridge-homematicip#22]
Hello all, 
First of all, thank you very much for your effort! Would it be possible to implement the alarm system function including siren? Thanks

**Comment by marcsowen** [comment]
What is the log showing for your device?

[HomematicIP] Device not implemented: ... ?

**Comment by Killtroy** [comment]
hmip-asir
![37EED03C-5F1B-4D06-B0CE-8AA4FCAF04D1](https://user-images.githubusercontent.com/78113408/106065392-89ce7980-60fb-11eb-95d9-0687e8672315.jpeg)
![31B3D84F-1CC0-4AD0-8284-0235CC8AC38A](https://user-images.githubusercontent.com/78113408/106065442-9eab0d00-60fb-11eb-86f9-0779849fcc04.jpeg)

**Comment by marcsowen** [comment]
The HmIP-ASIR doesn't have any useful things to setup or display. There is also no "siren" device in HomeKit that I know of. But you probably want to have the HomematicIP "security system" with all the different door/window sensors, presence sensors, sirens and alarm states implemented. This might work, but I need to look into it. In HomeKit you can arm/disarm the alarm of a security system which loosely corresponds to Alarm-Modus ("Unscharf", "Hüllschutz", "Vollschutz") in the HomematicIP App.

I will leave the issue open until I investigated a bit more.

**Comment by marcsowen** [comment]
Starting with version 0.3.0 the plugin supports a "Home Security System" device which controls the HomematicIP security systems including internal and external alarms.
