### ISSUE TITLE
Invalid request

### ISSUE THREAD

**Issue by hotdotdev** [marcsowen/homebridge-homematicip#223]
Hi,

Since today I get this error:

`Cannot lookup device: request={"clientCharacteristics":{"apiVersion":"10","applicationIdentifier":"homebridge-homematicip","applicationVersion":"0.5.2","deviceManufacturer":"none","deviceType":"Computer","language":"de_DE","osType":"Linux","osVersion":"5.10.63-v7+"},"id":"3014F7xxxxxxx"}, headers={"Content-Type":"application/json","Accept":"application/json","VERSION":"12","AUTHTOKEN":"","CLIENTAUTH":"xxxx"}, code=418, message=, json={"errorCode":"INVALID_REQUEST"} `

Do you know the reason?

**Comment by marcsowen** [comment]
Did you erase the "AUTHTOKEN" content or is it missing? Can you check your config whether "auth_token" is configured? Or do you want to retrieve a new auth token by pressing the blue button? Then please check whether you have configured a PIN in the HmIP cloud and also provide the "pin" setting in your config file.

**Comment by CrossOverRide** [comment]
I have exactly the same issue. I have the auth_token and implemented it in my config. I tried it several times....need help

**Comment by beckern** [comment]
Hello,
are there any update about this issue? I have the same problem with a new installed plugin, but with code 400. 
The Autothoken is in the config.json but no pin. 
The Homebridge is fresh installed and I need support. 
thank you. 
![Uploading A9B4B23D-1538-4D4D-8C01-16BED43ACEFF.jpeg…]()

**Comment by Marco-HH** [comment]
Same Problem here... I Need help :

[HomematicIP] Cannot request: url=https://srv03.homematic.com:6969/hmip/home/getCurrentState, request="{\"clientCharacteristics\":{\"apiVersion\":\"10\",\"applicationIdentifier\":\"homebridge-homematicip\",\"applicationVersion\":\"0.5.2\",\"deviceManufacturer\":\"none\",\"deviceType\":\"Computer\",\"language\":\"de_DE\",\"osType\":\"Linux\",\"osVersion\":\"5.10.63-v7l+\"},\"id\":\"3014F711A00003D8A993AA58\"}", headers={"content-type":"application/json","accept":"application/json","VERSION":"12","AUTHTOKEN":"<A53695D62F1DBF02C4721B986D8BC317CEA255ADEXXXXXXXXXXX>","CLIENTAUTH":"661134D100F3AD2D78AA4CBXXXXXXXXXXX"}, code=403, message=Forbidden
[15/11/2021, 22:40:48] [HomematicIP] HomematicIP response is incomplete or could not be parsed: false

**Comment by marcsowen** [comment]
@Marco-HH You try to use the plugin without an auth token. Did you do the pairing procedure by pressing the "blue button" on the access point? After that the "auth token" is displayed in the logs, copy it to you config.json ("auth_token": "<your API auth token>")

```
{
    "platform": "HomematicIP",
    "name": "HomematicIP",
    "access_point": "<your access point ID>",
    "pin": "<your PIN if set in the app>"
}
```

**Comment by Marco-HH** [comment]
@marcsowen Thx for the quick Answer. I did the pairing procedure, and I also change the line " "Pin": ....." into "auth_token": ""). The user also appear in the user list on the Homatic-ipapp, but it still doesn't work

**Comment by beckern** [comment]
The plug-in works in my homebridge. I wrote the wrong token an pin in the config.json.

**Comment by Marco-HH** [comment]
i found my mistake.... i forgot to remove "<>" ... Now everething is working great :-D
