### ISSUE TITLE
Replace Hue Wall Switches with Homematic HmIP-FCI6

### ISSUE THREAD

**Issue by modi80** [marcsowen/homebridge-homematicip#23]
I would like to replace the Hue Wall Switches and found the Homematic HmIP-FCI6 with 6 channels. Does is already work with your plugin?

**Comment by nsowen** [comment]
I was working on this, but unfortunately there is no such thing as a „button pressed“ event shown on the API. Maybe @marcsowen has further insights.

**Comment by modi80** [comment]
It really wouldn't be bad if it worked. I was not able to find an reliable alternative to the battery-free Hue Wall Switches.

**Comment by marcsowen** [comment]
I haven't checked yet but unfortunately the API really doesn't seem to provide button press events:

https://github.com/coreGreenberet/homematicip-rest-api/issues/346

Maybe it works, if you attach the button press event to some sort of automation which is processed by the HomematicIP cloud. I will look into it.

Another solution for you might be to use a real HmIP-Switch like HmIP-BSM. This device always feeds the state back to the HomematicIP-Cloud.

**Comment by steckenpferd** [comment]
What if you create an empty automation in the HomematicIP App and connect it with the button. Would that not work if you monitor than the triggered automation for HUE.

**Comment by modi80** [comment]
I could buy one and provide logs if it helps.

**Comment by marcsowen** [comment]
I tried even with automation and had no luck. I guess it's not working right now unless eq-3 decides to change the behavior. I will keep on trying though.
