### ISSUE TITLE
Door Lock Drive Türschlossantrieb HmIP-DLD

### ISSUE THREAD

**Issue by UrsLebowski** [marcsowen/homebridge-homematicip#238]
Is there a way to use a HmIP DLD? Log says it's not implemented.
"Device not implemented: HmIP-DLD - Türschlossantrieb via type DOOR_LOCK_DRIVE"

**Comment by marcsowen** [comment]
It's currently not implemented yet. I will look at it.

**Comment by UrsLebowski** [comment]
thank you for the fast feedback. that would be great!

LG

Urs

**Comment by adrianoje** [comment]
Lovely that would be great! I got one DLD at home - let me know if ai can help somehow. Thansk!

**Comment by UrsLebowski** [comment]
> Lovely that would be great! I got one DLD at home - let me know if ai can help somehow. Thansk!

Yes, exactly. If I can support or donate, I'm very happy.

**Comment by adrianoje** [comment]
Would be also more than happy to donate, keeping up the great work to have HMIP AP up to date integrated to homebridge (i‘m using it to have all of the devices in Homekit)

**Comment by marcsowen** [comment]
DLD is a bit tricky. I have a dump from coreGreenberet/homematicip-rest-api#406 but I don't know how to send the lock/unlock command yet. Maybe I need an additional dump of these commands. I will let you know.

**Comment by adrianoje** [comment]
Hey @marcsowen any news on the DLD dump? Anything you need support in? Thx

**Comment by marcsowen** [comment]
@adrianoje Would it be possible for you to intercept the locking/unlocking REST-API-Calls with your smartphone somehow? Last time I did this was by using an app like [Charles](https://www.charlesproxy.com) on my computer to intercept all traffic between the smartphone and the HmIP cloud.

I'm hesitating on buying one of those door locks myself since I will probably won't use it - and by the reviews it seems pretty noisy. Another option would be to lend your device to me for a couple of days for me to implement it initially.

**Comment by adrianoje** [comment]
Yes, I can send you the Doorlock for testing. Can you send me a PM? You are from Germany?

**Comment by marcsowen** [comment]
Sure, drop me an email at marcsowen+github@gmail.com

**Comment by UrsLebowski** [comment]
adrianoje was faster :) in that case I would like to donate something for the effort. If something comes up with adrianoje, I can also send the lock. LG Urs

**Comment by marcsowen** [comment]
@UrsLebowski Thanks for your support. @adrianoje lock should arrive any day now. I will let you know about the status.

**Comment by marcsowen** [comment]
Good news: I just released version 0.7.0 with initial support for the HmIP-DLD. You can lock and unlock but you can't open the door completely yet. HomeKit doesn't know this state for a regular lock mechanism. I will see if I can work something out.

Side note: Apparently Siri on a HomePod will let me lock the door - but won't unlock it unless I give approval on my personal iPhone.

Please test and thanks again @adrianoje for borrowing me his HmIP-DLD.

**Comment by UrsLebowski** [comment]
Großartig! Ich habe es schon ausprobiert, funktioniert super! Vielen Dank an euch beide!

Die öffnen-Funktion (das der Riegel eingezogen wird) könnte man doch mit einem Extra Stateless Switch lösen?

LG

Urs
Von meinem iPhone gesendet
Von meinem iPhone gesendet

Am 18.12.2021 um 17:54 schrieb Marc Sowen ***@***.***>:

﻿

Good news: I just released version 0.7.0 with initial support for the HmIP-DLD. You can lock and unlock but you can't open the door completely yet. HomeKit doesn't know this state for a regular lock mechanism. I will see if I can work something out.

Side note: Apparently Siri on a HomePod will let me lock the door - but won't unlock it unless I give approval on my personal iPhone.

Please test and thanks again @adrianoje<https://github.com/adrianoje> for borrowing me his HmIP-DLD.

**Comment by UrsLebowski** [comment]
Great! I have already tried it, works great! Many thanks to both of you!

The open function (which the latch is pulled in) could be solved with an extra stateless switch?

LG

Urs
Von meinem iPhone gesendet Von meinem iPhone gesendet

Am 18.12.2021 um 17:54 schrieb Marc Sowen ***@***.***>:

﻿

Good news: I just released version 0.7.0 with initial support for the HmIP-DLD. You can lock and unlock but you can't open the door completely yet. HomeKit doesn't know this state for a regular lock mechanism. I will see if I can work something out.

Side note: Apparently Siri on a HomePod will let me lock the door - but won't unlock it unless I give approval on my personal iPhone.

Please test and thanks again @adrianoje<https://github.com/adrianoje> for borrowing me his HmIP-DLD.

**Comment by marcsowen** [comment]
@UrsLebowski I will try to add another (stateless) switch. Problem is HomeKit is a bit picky about custom switches. The idea is that Siri wants to understand what the accessory is all about. If I add a "random" switch to some accessory, Siri wouldn't know what to do when saying "Open the front door" / "Unlock the front door" etc.

Another solution would be to add a config option like "pullLatchWhenUnlocking: true/false".

**Comment by UrsLebowski** [comment]
Good morning,
after a few tests I have found a problem after all.
Yesterday I only tested with one door lock, everything worked. But the second lock doesn't want:


  1.  Door lock “Mühlweg” - works –
[12/20/2021, 9:27:58 AM] [HomematicIP] Setting door lock drive Eingang Mühlweg to SECURED
[12/20/2021, 9:27:58 AM] [HomematicIP] Door lock drive motor state of Eingang Mühlweg changed to CLOSING
[12/20/2021, 9:28:00 AM] [HomematicIP] Door lock drive motor state of Eingang Mühlweg changed to STOPPED

2. Door lock “Markstrasse” - does not work
[12/20/2021, 9:27:55 AM] [HomematicIP] Setting door lock drive Eingang Marktstraße to SECURED
[12/20/2021, 9:27:55 AM] [HomematicIP] Cannot request: url=https://srv25.homematic.com:6969/hmip/device/control/setLockState, request="{\"channelIndex\":1,\"deviceId\":\"3014F711A0002A1BE9A793B6\",\"authorizationPin\":\"\",\"targetLockState\":\"LOCKED\"}", headers={"content-type":"application/json","accept":"application/json","VERSION":"12","AUTHTOKEN":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","CLIENTAUTH":"xxxxxxxxxxxxxxxxxxxxxxx"}, code=400, message=Bad Request



Both locks work in the Homematic app.

Do you have any idea what i can do?

LG Urs

[12/20/2021, 9:27:55 AM] [HomematicIP] Setting door lock drive Eingang Marktstraße to SECURED
[12/20/2021, 9:27:55 AM] [HomematicIP] Cannot request: url=https://srv25.homematic.com:6969/hmip/device/control/setLockState, request="{\"channelIndex\":1,\"deviceId\":\"3014F711A0002A1BE9A793B6\",\"authorizationPin\":\"\",\"targetLockState\":\"LOCKED\"}", headers={"content-type":"application/json","accept":"application/json","VERSION":"12","AUTHTOKEN":"A64A6CF991298948ADB58C362DA7F81460B43F3BFCEB4A2C07149A1F16548CA1","CLIENTAUTH":"F9EA1FDB57A03A199389A6F74262CE3152FEE72D8F13475B56E864B0D14581CDAF436383D4C023802F4C42228D41D4B4B26A2274702F5892358F6CF9864D0237"}, code=400, message=Bad Request

Von: Marc Sowen ***@***.***>
Datum: Samstag, 18. Dezember 2021 um 17:54
An: marcsowen/homebridge-homematicip ***@***.***>
Cc: Urs Lebowski ***@***.***>, Mention ***@***.***>
Betreff: Re: [marcsowen/homebridge-homematicip] Door Lock Drive Türschlossantrieb HmIP-DLD (Issue #238)

Good news: I just released version 0.7.0 with initial support for the HmIP-DLD. You can lock and unlock but you can't open the door completely yet. HomeKit doesn't know this state for a regular lock mechanism. I will see if I can work something out.

Side note: Apparently Siri on a HomePod will let me lock the door - but won't unlock it unless I give approval on my personal iPhone.

Please test and thanks again @adrianoje<https://github.com/adrianoje> for borrowing me his HmIP-DLD.

**Comment by marcsowen** [comment]
@UrsLebowski Maybe the second lock has a separate PIN assigned? Maybe you didn't give access to the homebridge-homematicip plugin for this particular lock. Check all settings on the settings page "Access" / "Access authorizations" (German: "Zutrittsberechtigungen"). I believe you can have different settings for different locks.

**Comment by UrsLebowski** [comment]
I'm speechless! Direct hit! Bugs found and fixed! Please send me your PayPal address to ***@***.***, then I would like to donate something ...

LG

Urs

**Comment by adrianoje** [comment]
@marcsowen, great idea with the switch. I think it would be also very useable: you could just add a scene in Homekit and name it „open front door“ and than add the switch to it. Whenever you are than saying „siri, open the front door“ the scene will be triggered and the switch will open the door. :-)

**Comment by adrianoje** [comment]
Just checked again (as I sold my Nuki Lock some months ago) usually in HomeKit you can only Lock or Open the door. An unlock functionality is missing (and i think also not that important on daily use). See here at 05:20.  
https://youtu.be/5xKY4hdoWJE

Would it be possible to map HMIP state „Öffnen“ to HomeKit „Ensperren“ and HMIP state „Lock“ to HomeKit „Sperren“.


If yes we would have the lock working as any other HomeKit Doorlock. :-)

**Comment by marcsowen** [comment]
@adrianoje From the video I can't really distinguish between "open" and "unlocked". It looks like the presenter is actually pushing the lever down after "unlock". I definitely make it at least configurable.

**Comment by adrianoje** [comment]
Yes, you‘re right the video does not show it. Found another test which explains it as i mentioned above - standard for HK for „Open“ is definitely to fully open the door.

https://www.loggn.de/test-nuki-combo-2-0-smartes-tuerschloss-mit-apple-homekit/

„ HomeKit besitzt beim LockMechanism leider nur zwei Status – Offen und Geschlossen.

Wenn das Schloss in HomeKit Geschlossen ist und man in HomeKit die Aktion ausführt, wird das Schloss geöffnet und bei meiner Konfiguration auch die Falle gezogen.
Wenn das Schloss in HomeKit Offen ist und man in HomeKit die Aktion ausführt, wird das Schloss geschlossen. Im Status Offen, kann man über HomeKit NICHT die Falle ziehen – man muss quasi erst zusperren und dann wieder öffnen.“

Interesting is also the explanation that If the door is not locked you can‘t open it via HK.

**Comment by marcsowen** [comment]
With version 0.7.1 I've added some options to the door lock. Please see Wiki for further details:

https://github.com/marcsowen/homebridge-homematicip/wiki

**Comment by adrianoje** [comment]
Great work! Chapeaux! :-)

**Comment by UrsLebowski** [comment]
Great job, thank you very much for that !!!

LG and have a nice Christmas

Urs

**Comment by gutschik** [comment]
> Another solution would be to add a config option like "pullLatchWhenUnlocking: true/false".

@marcsowen did you continue to work on that feature? can't seem to find that string anywhere in the code.
