### ISSUE TITLE
How to get it working with RaspberryMatic

### ISSUE THREAD

**Issue by reinisb** [marcsowen/homebridge-homematicip#243]
Hi folks,

I have a Raspberry Pi 3B with a clean install of Raspberry Pi OS. I also installed docker with two containers - one container runs RaspberryMatic, the other container runs Homebridge. I can access and manage RaspberryMatic and Homebridge through their respective web interfaces so both are working correctly.

I now installed homebridge-homematicip plugin through Homebridge web interface. The plugin is now asking to enter the homematicip config (screenshot below). In the [readme](https://github.com/marcsowen/homebridge-homematicip#readme) I see that I need values for `access_point` and `auth_token` or `pin`. Can you please let me know how I can get those from RaspberryMatic? I tried google but nothing comes up.

Thank you!

<img width="1034" alt="Screen Shot 2021-12-01 at 23 49 40" src="https://user-images.githubusercontent.com/6346595/144319727-b93b19a6-c9f7-4848-b693-24e00a230ec5.png">

**Comment by marcsowen** [comment]
Hi @reinisb ,

I'm not sure whether your plan works. The plugin was designed to be used in conjunction with the HmIP-AccessPoint, not a CCU. As far as I understood, RaspberryMatic is just a replacement for the CCU. If you want to use Homebridge together with a CCU (or a CCU clone), you need the following plugin: https://github.com/thkl/homebridge-homematic. Even though the plugin has no "IP" in the name, it does work with HmIP devices.

If you happen to have a HmIP-AccessPoint, you don't need RaspberryMatic. Just use Homebridge with the homematicip plugin and add the following config:

- **access_point**: It's printed as "SGTIN" on your HmIP-AccessPoint
- **pin**: Optionally the PIN you entered as "System-PIN" in your HmIP-Smartphone-App.

When starting Homebridge with these settings, you will see a message in the logs to press the "blue button" on the HmIP-AccessPoint. After doing so, you will get an auth_token displayed in the logs. Use this **auth_token** in the config and restart the plugin. You may remove the **pin** again, since it's not needed anymore (for now).

**Comment by reinisb** [comment]
Hey @marcsowen,

I really appreciate your detailed response. Yes, RaspberryMatic is a replacement for CCU - in fact, I already tried the [homebridge-homematic](https://github.com/thkl/homebridge-homematic) plugin and while it does work, it is generally pretty buggy and in most cases, I will see the "No response" error. That's why I am looking for a more solid solution, and it seems that your plugin should be a lot more stable.

Alright, so just to confirm. You're saying that I don't need a CCU3 or RaspberryMatic at all, but I can simply purchase the [HmIP-AccessPoint](https://www.amazon.de/-/en/Homematic-IP-Access-Point-140887A0/dp/B00ZQG6MGO) and then homebridge+your plugin will be able to communicate to HmIP-AccessPoint and control the HoemamaticIP devices? If so, will I need to subscribe to any paid homematic cloud service (I assume not, but just want to be sure)? Also, I now don't really understand why would anyone want to buy CCU3 instead of just buying the HmIP-AccessPoint - does the access point have any limitations?

Thanks,
Reinis

**Comment by marcsowen** [comment]
> You're saying that I don't need a CCU3 or RaspberryMatic at all, but I can simply purchase the HmIP-AccessPoint and then homebridge+your plugin will be able to communicate to HmIP-AccessPoint and control the HoemamaticIP devices?

Yes. But only HomematicIP devices. Not regular (older) Homematic devices, which are still supported by the CCU.

> If so, will I need to subscribe to any paid homematic cloud service (I assume not, but just want to be sure)?

No, it's free - or in other terms: You paid for it already with the purchase of your HomematicIP devices. They guarantee at least 10 years of service, if I remember correctly.

> Also, as far as I understand HmIP-AccessPoint communicates through Homematic cloud servers, right?

Yes.

> If Homematic shuts down their servers one day, then also your plugin will not be able to communicate with HmIP-AccessPoint anymore, right?

Correct. Also if eQ-3 decides to change the API/protocol and make sure I can't reverse engineer it, it will stop working. So your only guarantee is that the HomematicIP app will probably work for the next 10+ years.

**Comment by reinisb** [comment]
Gotcha, this sounds really good! I'm going to purchase the access point and give it a go! I really hope that your plugin will be stable and not have those "Not response" errors in Home app.

PS I currently only have one Homematic IP accessory (and none older Homematic accessories) - it is the HmIP-MOD-HO (I see you discussed it [here](https://github.com/marcsowen/homebridge-homematicip/issues/14)).

**Comment by thecem** [comment]
I can confirm that homebridge with this plugin is stable!

**Comment by marcsowen** [comment]
@reinisb I guess you can always send it back if it's not working out for you. I use the plugin 24/7 and it seems to be stable. Which is mostly due to the excellent HmIP cloud having an uptime of nearly 100%.

**Comment by reinisb** [comment]
Hey @marcsowen ! I wanted to share a quick update. For more than a year the combination of HmIP Access Points + HmIP garage door module + homebridge-homematicip was working perfectly fine. Until a few days ago it stopped working. I checked the HomematicIP app in the iPhone and the garage door module does show up (has decent radio connection), but it is not possible to control it anymore. I reached out to eq-3 support and they told me that the most likely culprit of the corruption is that I've been using unofficial third party software (homebridge-homematicip) to interact with the access point. They recommend resetting both the access point and the garage door module and then use it only through the HomematicIP app on my iPhone.

Have you ever experienced this before?

**Comment by marcsowen** [comment]
Hi @reinisb ,

this is odd. eq-3 is definitely quite strict with access to their API. Especially when you send too many requests per second. But usually eq-3 will reset everything to normal after about an hour. The plugin should throttle all requests to the API automatically so usually you don't have to worry about it. But maybe eq-3 changed the limits again?

Have you tried waiting for about an hour and then maybe restart homebridge completely? Maybe some other device/daemon is using the same access token? And maybe your whole IP address is temporarily on eq-3's blacklist. But this should also be resolved within an hour.

Last resort would be to generate a new access token. But this only works if you IP is not blocked. Don't expect any help from eq-3. They seem to tolerate this but will avert any support calls / emails, which I completely understand.

**Comment by reinisb** [comment]
Hey @marcsowen ! Thanks for the response. I don't think that anything broke between Access Point and 
homebridge-homematicip. Instead, it looks like something broke on HomematicIP end since the accessory simply stopped working. The funny thing is that I woke up this morning and it works again. I bet HomematicIP team realized the issue and fixed it.

**Comment by marcsowen** [comment]
Good to hear! 👍
