### ISSUE TITLE
Current Relative Humidity 

### ISSUE THREAD

**Issue by LPhilipp2408** [marcsowen/homebridge-homematicip#244]
Hi,
I'm not seeing the "Current Relative Humidity" value that is displayed in the configuration of a HmIP-BWTH on the icorn (not on homebridge neither on the Homekit App). Can this be added somehow?

Thermostat	
Current Heating Cooling State	0
Target Heating Cooling State	3
Current Temperature	20.9°
Target Temperature	17°
Temperature Display Units	0
**Current Relative Humidity	60%**
Manufacturer	eQ-3
Model	HmIP-BWTH
Name	Wandthermostat Küche
Serial Number	XXXXXXXX
Firmware Revision	1.2.4
Homebridge Instance IP	XXXXXXX
Homebridge Instance Port	XXXX
Homebridge Instance Username	XX:XX:XX
aid	10
iid	14

**Comment by marcsowen** [comment]
Hi @LPhilipp2408 ,

the relative humidity is displayed in the Home app when opening your thermostat and go to the device settings page. Unfortunately it is not shown directly on the icon for thermostats. This is design decision by Apple. The Eve app displays it more prominently and also supports a graph showing temperature and humidity over time.

**Comment by LPhilipp2408** [comment]
Hi @marcsowen
Thanks for the quick answer and explanation. 
I was hoping I could see that value within the home app directly and not via the device settings.
