### ISSUE TITLE
HmIP-MOD-HO remove light switch

### ISSUE THREAD

**Issue by reinisb** [marcsowen/homebridge-homematicip#253]
Hi folks!

I'm using the plugin to control my Hörmann RotaMatic gate through HmIP-MOD-HO (yes, it is designed to work not only with SupraMatic garage doors but also RotaMatic gates).

The plugin works great, but there is one problem. You see, unlike the SupraMatic garage door unit that has a built-in light, the RotaMatic gate unit does not have a built-in light (the light is an optional accessory). Hence having the light switch show up in a combined accessory is very confusing. I'd really like to remove the light switch from the combined accessory.

Could you please let me know how to achieve that? Ideally, there would be a setting in the plugin that would allow me to specify whether my Hormann unit has a light or not.

Alternatively, I could edit the source code files on my Raspberry Pi running Homebridge, but then I would need to have clear instructions on how to do that. I tried removing all lines that mention`switchService` from [HmIPGarageDoor.ts](https://github.com/marcsowen/homebridge-homematicip/blob/master/src/devices/HmIPGarageDoor.ts) stored at my RaspberryPi, but that did not work and I still see the light switch. I guess I'm missing some point. Could you please help? 

Thank you!

![maxresdefault-3](https://user-images.githubusercontent.com/6346595/146636377-8afe1e93-7e56-4083-9180-3ede3fde1fe0.jpg)

**Comment by marcsowen** [comment]
Hi @reinisb ,

you will need to remove all reference to switchService from the HmIPGarageDoor class and then also remove the device from cache. If you have the Homebridge UI plugin installed, you can click on the three vertical dots on the upper right hand corner, click on Homebridge settings and scroll down until you see the Cache settings. There, remove you garage door and restart Homebridge. The garage door should be re-created on next plugin start and the switchService should not appear anymore.

I will try to make it configurable in one of the next versions.

**Comment by reinisb** [comment]
Hi @marcsowen ,

Thanks for the response. So actually I already tried what you suggested yesterday, but it did not work. Most likely there is some extra step I need to take. Here is what I did:
1. In Homebridge UI I pressed `Disable` at the Homebridge Homematicip plugin.
2. Then I SSHd into raspberry pi and `run sudo nano /usr/lib/node_modules/homebridge-homematicip/src/devices/HmIPGarageDoor.ts`
3. Then in that file I removed mentions of `switchService` (lines [44](https://github.com/marcsowen/homebridge-homematicip/blob/ebf99121bfd207de2a58c4377d130922f2f7d30d/src/devices/HmIPGarageDoor.ts#L44), [73-77](https://github.com/marcsowen/homebridge-homematicip/blob/ebf99121bfd207de2a58c4377d130922f2f7d30d/src/devices/HmIPGarageDoor.ts#L73-L77), and [152](https://github.com/marcsowen/homebridge-homematicip/blob/ebf99121bfd207de2a58c4377d130922f2f7d30d/src/devices/HmIPGarageDoor.ts#L152)). 
4. In Homebridge UI under Homebridge Settings I pressed Remove All Cached Accessories
5. I restarted Homebridge
6. In Homebridge UI I pressed `Enable` at the Homebridge Homematicip plugin.
7. The accessories showed up, but the garage door light switch was still present.

**Comment by marcsowen** [comment]
@reinisb I will introduce a config option in one of the next versions.

**Comment by reinisb** [comment]
> @reinisb I will introduce a config option in one of the next versions.

That's awesome, thank you! I'm really looking forward to that. PS Is there a donate button somewhere?

**Comment by marcsowen** [comment]
@reinisb Please try version 0.7.2 and add the option "lightSwitch": false to your device. Please see the [Wiki](https://github.com/marcsowen/homebridge-homematicip/wiki) for details.

**Comment by reinisb** [comment]
@marcsowen It worked perfectly - thank you!
