### ISSUE TITLE
Very large number of log entries

### ISSUE THREAD

**Issue by Perilax-De** [marcsowen/homebridge-homematicip#256]
The log entries for the radiators or even for the shutters are really a lot.

Perhaps you could reduce the log entries or omit them altogether.

![image](https://user-images.githubusercontent.com/75173766/147383399-ec5bc04e-4d4b-443f-910d-8ed8d42a5e46.png)

![image](https://user-images.githubusercontent.com/75173766/147383403-9e57168d-5679-4e74-9d15-6ca55e3f4ff5.png)

**Comment by marcsowen** [comment]
Hi @Perilax-De,

yes, you're right. I reduced the verbosity with version 0.7.2. Please let me know whether this is better or not. :-)

**Comment by Perilax-De** [comment]
Thank you for implementing my suggestion. Good job done @marcsowen
Now only the important information is displayed in the log.

![image](https://user-images.githubusercontent.com/75173766/147731559-2a7c766d-d42b-459e-abfd-b5d2c0eaee26.jpeg)
