### ISSUE TITLE
HmIP-BBL not implemented

### ISSUE THREAD

**Issue by dermax** [marcsowen/homebridge-homematicip#26]
Hi, 
i stumbled across your project after parting with io broker...
i think that the BBL is pretty much the same as the BROLL shutter switch. how do i, at least do a workaround that i can use the HmIP-BBL as a BROLL ans it does not get excluded as "Device not implemented: HmIP-BBL" 

Thanks in advance.

**Comment by nsowen** [comment]
Guten Tag und vielen Dank für Ihre Nachricht!

Ich befinde mich aktuell in Elternzeit und bin voraussichtlich ab dem 1. April 2021 wieder für Sie erreichbar. Bitte wenden Sie sich an Dirk Vleugels (dvl (at) 2scale.net).

Viele Grüße,

Nils Sowen

**Comment by marcsowen** [comment]
Actually I just realized that BROLL is also not yet supported. I need to implement the slat behavior first. It should be available including BBL in a couple of days.

**Comment by marcsowen** [comment]
Try version >0.1.3. I have implemented it without testing. Can you check if it works?

**Comment by dermax** [comment]
Just updated.
I just have the BBLs to test.
So the slats level (Stellung der Jalosien Blätter) is still a little crooked... UP. Down. works perfectly and every position from 0 to 100 is reachable, but the slats level (i just read those values from iobroker) is controlled from 1 (totally shut) to 0 (horizontally open) this is only for the BBL (Blindsactuator for Raffstores/Jalosien(german)) a function not used on the BROLL. Otherwise, thanks very much for the fast implementation. Drop me a paypal, I'd gladly gift you some €€€!

All the best, Max.

**Comment by marcsowen** [comment]
Can you be a bit more specific on what is crooked? HomeKit has a slat position between -90 and 90 degrees. I mapped the angels to the HomematicIP values between 0 and 1 (-90 -> 0.0, +90 -> 1.0). Maybe this isn't right. Which angle should be open? Or should it be the other way around (-90 -> 1.0, +90 -> 0.0)?

**Comment by dermax** [comment]
I just did some testing. As soon as i touch the slats slider on the iphone, the blinds go up all the way and the slats level is then adjusted at blinds level 0%. so something's wrong there. If the blinds level is 100% and i force touch the percent slider the slats go to about 45deg open...wierd.

**Comment by thecem** [comment]
Same problem was for the shelly shutter, you have to implement a function that set the state after the release the slider, or at least a delay, to prevent immediate changes.

**Comment by marcsowen** [comment]
The problem is that the Rest call for changing the slats also changes the shutter level. I didn't set the shutter level assuming it would stay where it is. But apparently it assumes shutter level 0 (open). I changed it to the last known shutter level in version >= 0.1.5. Please try.

**Comment by dermax** [comment]
Sorry for the late reply.
I tested the new version. still the same, as soon as i touch the slider button it goes to blindlevel 0 and there i can use the slatslevel perfectly, just not anywhere else...

**Comment by marcsowen** [comment]
Did you move the shutter level (up/down) before changing the slats level? The initial level is actually 0 but is updated as soon as we get that information from the HmIP-Cloud. It might take a couple of seconds/minutes to get the first update depending on the device. You can see an update in the logs:

`Current shutter level of ... changed to ...`

**Comment by dermax** [comment]
You are right, after a homebridge restart and a move from 0 to 100, it works absolutely fine at any level. Thank you!

**Comment by marcsowen** [comment]
Glad to hear!

**Comment by dermax** [comment]
Only thing that is left, is that when the slats slevel is shut i always have the "spinning loading graphic" in the richt upper corner of the homekit button.  
![IMG_8670B3D1FE7B-1](https://user-images.githubusercontent.com/3296663/107012296-21396980-6799-11eb-9b2d-204fb07e0578.jpeg)

**Comment by marcsowen** [comment]
Can you look at the logs and see if the value "Setting target horizontal slats position..." and then finally the value of "Current blind slats level..." is identical?

**Comment by dermax** [comment]
After the highlited part i changes the slats to clodes (90deg) at 50% shutterlevel, it'Äs also strange that the "loading icon" disapears after some operations with the slats level.


<img width="1007" alt="Bildschirmfoto 2021-02-05 um 15 15 24" src="https://user-images.githubusercontent.com/3296663/107044735-ffee7280-67c4-11eb-81ec-8d4dfb940e42.png">

**Comment by marcsowen** [comment]
Basically HomeKit gets the correct events. You requested 90 degrees and the slats reach 90 percent after a few seconds. That should satisfy HomeKit - but sometimes it doesn't. Same with the shutter level. I think the "loading icon" indicates that something is moving.

I only have a simple shutter without slats but I will try to find pattern on when the "loading icon" disappears.

**Comment by marcsowen** [comment]
Can you try version >= 0.2.3? I might have improved the behavior.
