### ISSUE TITLE
HMIP Alarm State / Mapping to HomeKit broken

### ISSUE THREAD

**Issue by adrianoje** [marcsowen/homebridge-homematicip#285]
Hey! Somehow since i updated to iOS 15.3 disabling the alarm (select Aus/Off) state via HomeKit results in switching off the Alarm State in HMIP correctly (Unscharf) BUT it switches in the HomeKit app immediately to „Zuhause / At Home“ afterwards? 
If i‘m selecting than afterwards again „Off / Aus“ in Homekit it stays in „Off/Aus“ and does not switch back to „Zuhause / at home“ automatically. can someone please test if they have the same issue? Thanks!

**Comment by marcsowen** [comment]
Yes, I can reproduce the problem. Somehow the updates are not working correctly. But the commands are send correctly. I will have a look.

**Comment by adrianoje** [comment]
Great! Thanks!

**Comment by adrianoje** [comment]
Is the root cause iOS related? There has been an update to iOS 15.3 at that stage. 

Thanks!

**Comment by adrianoje** [comment]
Please close this issue, iOS 15.4 has fixed it. thanks! :-)

**Comment by adrianoje** [comment]
Sorr. My fault, anfortunatel. IOS 15.4 did NOT fixed the issue. @marcsowen so we still need your help on here :-)

**Comment by adrianoje** [comment]
@marcsowen hope things are going well at your end? :-)
Any chance to get this bug fixed? Would be more than happy to help in any aspect… :-)

**Comment by marcsowen** [comment]
@adrianoje I'm alive and terribly sorry for the long delay. I'm trying to release a new version but I don't find much time to work on the project at the moment. I will keep you updated as soon as a new version arrives.

**Comment by adrianoje** [comment]
Nice hearing from you! Thanks! As always highly appreciated :-)

**Comment by adrianoje** [comment]
Hope everything is fine at your end :-)
Just wanted to ask if you have some plans to bugfix the alarm state topic? thinking to switch maybe to switch from Hmip to some native homekit alarmsystem. But not before first threat enabled sensors etc are avaible :-)

**Comment by marcsowen** [comment]
@adrianoje I debugged the issue. Problem is, HomematicIP sends the group updates for the external and internal security zone independently. Apparently, when you change the settings in a way, that both zone states are changed (e.g. from away alarm to off), the plugin first receives the event that the internal zone is switched off. Right after that the plugin updates the HomeKit states resulting in a STAY_ARM state. Only after that the second event (external zone => off) will be updated.

Apparently only the first event will be shown in the app. It takes a couple of minutes until HomeKit realizes the correct state. One solution might be to delay the first event and wait for a second. But this also delays the update in the Home app altogether. I'll think about it...

**Comment by adrianoje** [comment]
Thanks for the update and explanation! :-) and good to hear you are doing well :-)

**Comment by marcsowen** [comment]
@adrianoje Please checkout 0.8.0-beta.2. I think I fixed the problem.

I also played around with the package manager - now using pnpm instead of npm. I still don't know whether this is a good idea. Let me know whether there are problems installing the plugin.

**Comment by adrianoje** [comment]
@marcsowen thanks! any chance to update from 0.72 straight to the beta via HOOBS? Just to prevent i need to reassign all devices new in HomeKit. (if not no worries, than i will add the beta a new bridge) :-)

**Comment by adrianoje** [comment]
@marcsowen new version works great! I tested all of my devices and they are working as they should work in HomeKit (so nice everything is fine again). Massive thanks to you! Cheers!

**Comment by marcsowen** [comment]
Great to hear! Thanks for testing!
