### ISSUE TITLE
Homebridge link to Homekit

### ISSUE THREAD

**Issue by BDSchultze** [marcsowen/homebridge-homematicip#307]
I have Homebridge installed on my NAS (Synology) and I try to install the Bridge to Apple Homekit. 
My HomeKit say: "Gerät ist bereits hinzugefügt Um dieses Gerät zu deinem Zuhause hinzuzufügen, musst du es zuerst zurücksetzen."

How can I reset Homebridge in my Homekit?

Can you help me? Sorry about my english!

**Comment by marcsowen** [comment]
To reset everything homebridge related, you need to find the config directory (try ~/.hombridge or /var/lib/homebridge) and remove the **persist** and **accessories** directories. Please make sure homebridge is not running before doing so.

**Comment by BDSchultze** [comment]
Thank you, it was very helpful!
