### ISSUE TITLE
Update to 0.2.0

### ISSUE THREAD

**Issue by modi80** [marcsowen/homebridge-homematicip#33]
Hey, i wanted to update to 0.2.0 but it was not working via Hoobs Update. So I removed the plugin and tried to reinstall, but now I am getting this:

5.2.2021, 10:57:23 npm5.2.2021, 10:57:23  ERR! code ETARGET5.2.2021, 10:57:23 npm5.2.2021, 10:57:23 ERR! notarget No matching version found for homebridge-homematicip@0.2.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.5.2.2021, 10:57:23 5.2.2021, 10:57:23 npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-02-05T09_57_23_022Z-debug.log

**Comment by marcsowen** [comment]
Yeah, sorry. I needed to pull 0.2.0 since it had a dependency bug I haven't resolved yet. The latest version is still 0.1.5. I will fix it as soon as possible.

**Comment by modi80** [comment]
Ah, ok. :) Can I tell Hoobs to download an older plugin version? Otherwise I would wait :)

**Comment by marcsowen** [comment]
Oh, I don't know. They still seem to show version 0.2.0 on their website. I'll try to hurry...

**Comment by modi80** [comment]
No hurry! I have definitely to thank you for your whole work here!

**Comment by modi80** [comment]
0.1.5 is online again via Hoobs. Thanx!

**Comment by marcsowen** [comment]
0.2.1 with the bug fix is out.

**Comment by modi80** [comment]
installed it and it works now. thank you

**Comment by marcsowen** [comment]
Great!
