### ISSUE TITLE
HMIP-BSL

### ISSUE THREAD

**Issue by DerBoeck** [marcsowen/homebridge-homematicip#332]
Please add Support for the Wall-Switch HMIP-BSL

thanks

**Comment by smhex** [comment]
@DerBoeck which features do you need? I have a switch now and will try to implement it...

**Comment by DerBoeck** [comment]
For me, i only need to control the switch to power on or off my light, the other features i don‘t need to control via HomeKit…

**Comment by smhex** [comment]
Okay, I have already implemented the switch service on my fork. I hope to create a PR soon....

**Comment by DerBoeck** [comment]
Cool 👍

**Comment by 1emc** [comment]
Looking forward to this feature

**Comment by smhex** [comment]
Created PR #389 to support the HMIP-BSL. 

@marcsowen : can you please review and merge the PR? Feel free to add your comments. In case everything is fine I can update the Wiki for the new configuration switch. Thank you!

**Comment by smhex** [comment]
Merged
