### ISSUE TITLE
[HomematicIP] HmIP websocket error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by MaxiKingXXL** [marcsowen/homebridge-homematicip#34]
The homebridge  HomematicIP connection stopped this morning and I large number of connection retries in the log. Every few seconds it tried to reconnect.
I have stopped homebridge and after a while I was able to connect again. 

I read that your IP might get blocked if you overuse the HomematicIP API. Might that be the issue?

From my home network the HomematicIP App also was blocked. A mobile connection using the same HomematicIP App worked properly at the same time.

**Comment by marcsowen** [comment]
Yes, that happened to me once as well. From my measurements your IP will be blocked for exactly 60 minutes, when you fire too many requests per second. One candidate ist the slider of the Eve app, which fires several tens of requests per second while moving.

I have it on my list to limit the amount of requests per second. Sorry for the inconvenience!

**Comment by MaxiKingXXL** [comment]
No issue. Thanks for you great work on this project.

Can you also control the connect retry delay? Currently it retries every few seconds. I assumes you are not unblocked when the plug-in tries to reconnect that frequently.

**Comment by marcsowen** [comment]
Please install version >= 0.2.2. I added a rate limiter allowing roughly two API calls per second. I hope eq-3 will be satisfied with these settings. Otherwise I need to tune it a bit more if this happens again. Let me know how it works out for you.
