### ISSUE TITLE
HmIP-SLO - outdoor sensor not implemented

### ISSUE THREAD

**Issue by smarthome43372** [marcsowen/homebridge-homematicip#35]
Firstly many thanks for great implementation of HmIP-HO. 
Would be really happy if you could also implement HmIP-SLO outdoor brightness sensor.

**Comment by marcsowen** [comment]
Sure. I checked the HmIP-API and the device seem to give the following information:

- averageIllumination
- currentIllumination
- highestIllumination
- lowestIllumination

The HomeKit "light sensor" seems to support a single "CurrentAmbientLightLevel" measured in _lux_ between 0.0001 and 100000.

By looking at the HomematicIP-App, can you tell me:

- is _average_ or _current_ illumination better suited for current ambient light level?
- are there any information about the unit of the measurements? Are the values also in _lux_ or something else?

Thanks!

**Comment by marcsowen** [comment]
Check out version >= 0.2.2. I use the the average value as you suggested. Please check if this works out for you.

**Comment by smarthome43372** [comment]
Works perfect. The value shown in HomeKit is exactly the same shown in HMIP App. Thank you so much. 
![image](https://user-images.githubusercontent.com/62788072/107834558-b4286400-6d96-11eb-8f9d-277481536c7b.png)

![image](https://user-images.githubusercontent.com/62788072/107834562-ba1e4500-6d96-11eb-8dbf-2ed1a7b5b11d.png)

**Comment by marcsowen** [comment]
Perfect!
