### ISSUE TITLE
Support for HmIP-DLS

### ISSUE THREAD

**Issue by smhex** [marcsowen/homebridge-homematicip#353]
Hi, the door lock sensor HmIP-DLS is not yet listed as supported device. Does someone know what happens when this sensor is connected? Is there a plan to support it officially in the plugin?

Thanks

**Comment by smhex** [comment]
Implemented in #357

**Comment by smhex** [comment]
I just installed the new version. At least for me everything works as expected 😃. Thanks for merging!

**Comment by marcsowen** [comment]
I just released version 0.8.0 with your patch.
