### ISSUE TITLE
Device not implemented: HmIP-HAP - Access Point via type HOME_CONTROL_ACCESS_POINT

### ISSUE THREAD

**Issue by sannc** [marcsowen/homebridge-homematicip#39]
Hi!

Thanks for this awesome plugin which generally works like a charm :-) However, since right after the installation I get the following warning:

`Device not implemented: HmIP-HAP - Access Point via type HOME_CONTROL_ACCESS_POINT`

Everything seems to work, though and as far as I can see, HmIP-HAP should be supported. What is the best way to solve this?

My environment:

- Homebridge v1.1.7 on a Raspberry Pi 4
- Node.js Version	v14.15.4 
- homebridge-homematicip v0.2.1

Thank you in advance!

**Comment by marcsowen** [comment]
Great to hear everything works just fine.

Don't worry about the message. After eQ-3 decided to support more than one access point the HAP devices showed up as a real device. The plugin used to show the HAPs as "light bulbs", where you could change the brightness of the HAPs illuminated blue button, but this was just too confusing.

Just ignore it. :)

If you have any more unsupported devices, please open up an issue (for each unsupported device) and I will see if I can support it in the next version.

**Comment by The-Tabsi** [comment]
Hey 
HmIP-SWDM / HMIP-SWDM 
no battery status ?
