### ISSUE TITLE
Wall Thermostate / Thermostate state cannot be changed

### ISSUE THREAD

**Issue by Boerdi0602** [marcsowen/homebridge-homematicip#398]
Hi,

As the new heating phase starts I started to use only Apple Home with Homebridge and HMIP.

I tested everything and encountered a problem:

If changing the temperature of wall thermostate or the heating thermostate the other one will change its temperature too - so far so good. But the room will only heat about 0,5 less as the given temperature. Also the temperature in Apple Home and HMIP will show only 19,5 and not the given 20 degree. Can a offset of 0.5 degree be created?

Question:
As I was not able to change the offset, I tried to change the state while heating to "HEAT" (Automation or manually in Apple Home) - to check wether it will heat the room to 20 degree or not.
It changes its status to "heating 20 degree" not "set 20 degree". Closing and reopen the app will bring the message "set 20 degree" and the state of the thermostate changes back to "Auto" not "HEAT".
(changing the mode in HMIP-App will not bring any improvements)

I checked the logs and it says (Examples):

[02/10/2022, 20:28:42] [HomematicIP] Ignoring setting heating/cooling state for Heizkörperthermostat to OFF
[02/10/2022, 20:47:20] [HomematicIP] Ignoring setting heating/cooling state for Heizkörperthermostat to HEAT
[02/10/2022, 20:49:02] [HomematicIP] Ignoring setting heating/cooling state for Heizkörperthermostat to COOL
[02/10/2022, 20:49:04] [HomematicIP] Ignoring setting heating/cooling state for Heizkörperthermostat to AUTO

Is there a possibility to change that (configuration file etc)? Not only deleting/not showing it in the logs. 

Thank you in advance!! :)

**Comment by marcsowen** [comment]
Try version 1.1.0-beta.2 which includes some changes in the heating/cooling state behavior. As far as offset is concerned, I don't really use it so it's not really tested well. I remember some discussions about that topic a while ago (search through the closed issues). As far as I remember, most people agreed that the current behavior is correct. But I might be wrong.

**Comment by Boerdi0602** [comment]
Looks much better. Thanks a lot!
