### ISSUE TITLE
No status update in home app

### ISSUE THREAD

**Issue by lion33319** [marcsowen/homebridge-homematicip#41]
Installed the plugin via hoobs. Everything works fine.
However, the home app doesn’t show me any status updates of my homematic ip shutters.
Next to each shutter, I get a rotating circle. When I press on the actual button of the shutter within the home app, the current status is updated and shown.
What do I need to do to get the current status displayed within my apple home app?

**Comment by marcsowen** [comment]
Hi. Unfortunately I'm still a bit puzzled why this happens. I definitely send out a shutter STOP state when shutter/blind stops processing. Most of the time the rotating circle stops within seconds. But sometimes it goes on for hours. Can you check with the EVE app if the values shown there make any sense?

Unfortunately the HmIP-Cloud doesn't send too many updates while the shutter is moving. In my case it sends out a few position updates in the first one or two seconds but then stops updating until processing stops. You can follow the updates in the logs.

**Comment by marcsowen** [comment]
Can you try version >= 0.2.3 and see if it is better now? Please make sure the plugin runs for a while and the shutter actually moved while running. The states might be wrong after startup.

**Comment by lion33319** [comment]
Wow... works like a charm! Great to see the fast reaction and fix!
Only one minor nitpick: when I press the physical homematic switch to either let the shutters roll up or down, the HomeKit app doesn’t show the status of the shutter. so, if the shutter moves to the fully open position, the app still shows closed. When i exit the app and reenter it however, the correct position of the shutter is shown. Is that normal?

**Comment by marcsowen** [comment]
It's normal that you don't get many updates while the shutter is moving. But you should definitely get an update when you reach the end position. Depending on your shutter, the end position is automatically determined by the circuit or it will count the number of seconds and signal the end position when the seconds are up. You need to make sure that you configured the right movement time in seconds in the HomematicIP App.

If you set everything up, have a look at the logs of the plugin. They signal the events coming from the cloud. A change of current position is shown with the log output:

`Current shutter level of xyz changed to xx`

When the shutter has reached the end position, you should get a log saying something like:

`Processing state of shutter/blind xyz changed to **false**`

If you don't see it, something isn't configured right in the HomematicIP app.

**Comment by thecem** [comment]
@lion33319 I tested the new function to use "ciao" insted of "bonjour HAP" as backend in homebridge. May you could test this beahvior with homebridge and chosse "ciao" under homebridge settings.
"Ciao" is much more faster and gives home the ability of nearly "live" status updates.

What happens when you close home, activate the plane mode and then deactivate and opens home?

**Comment by marcsowen** [comment]
@lion33319 Does the problem still exist?

**Comment by lion33319** [comment]
Hi,
nice work. The problem seems to be solved now.
However, I noticed that when you go into a specific blind (you get the little popup screen where you can select the closure level of the blind by swiping), that the blind reacts as soon as you touch the display. 
however, you should first be able to select the level of closure by swiping before the blind actually starts moving.

**Comment by marcsowen** [comment]
I'm afraid I can't change the behavior of the Home app. The app seems to update the position as soon as the slider moves. In general this is not a bad behavior, since in a local (non-cloud) environment, you could see the blinds move while swiping your finger across the screen. Feeding the commands through a (slow) cloud service was never the intention of Apple.
I already reduces the amount of commands which are send to the cloud to two commands per second, but this is all I can do right now.

**Comment by lion33319** [comment]
Don’t worry. works good enough! 
I noticed in your new version, that there is an option within HomeKit to turn on an alarm system.
I have the Homematic IP external alarm siren (HmIP-ASIR-O). Unfortunately, this does not seem to be compatible with your current version.
Are there any plans to implement the siren with your next version?

**Comment by marcsowen** [comment]
The siren itself cannot be directly supported by HomeKit. But this is not really necessary. We use HomematicIP's alarm system directly. We just turn it on or off in HomeKit and even receive alarms (e.g. when the siren is turned on). The interconnection between HomematicIP cloud, door/window sensor, motion detector, siren etc. is managed by HomematicIP.

So in short: The siren is already (indirectly) supported in HomeKit even though the log say something about an unsupported device.

**Comment by Multisaft7** [comment]
So I am not able to trigger the HmIP-ASIR-O siren with other devices directly from the homekit?

**Comment by marcsowen** [comment]
Currently I don't know of any endpoint in HomematicIP cloud that could trigger a "manual" alarm. Sorry. :(
