### ISSUE TITLE
HMIP-PSM HmIP-BROLL reporting battery state

### ISSUE THREAD

**Issue by mike4president** [marcsowen/homebridge-homematicip#43]
hi first of all, thank you for the plugin. I am using it within Hoobs and I love it so far. It is so much easier to setup the Homematic Devices using the Access point. 

What I noticed is, that your plugin reports battery states for HMIP-PSM and HmIP-Broll which doesn't make sense since these are 230v devices. Can you fix this?

**Comment by mike4president** [comment]
![IMG_0178](https://user-images.githubusercontent.com/65063329/107878154-02418280-6ed1-11eb-8e54-3e8af6b203aa.PNG)
![IMG_0180](https://user-images.githubusercontent.com/65063329/107878157-0372af80-6ed1-11eb-87c2-14bc4779b245.PNG)

**Comment by marcsowen** [comment]
Yes, good point. I'll have a look at it. It will probably take a couple of days.

**Comment by mike4president** [comment]
thanks, it is not a big deal. But other might notice this as well. Thanks for your effort

**Comment by marcsowen** [comment]
Starting with version 0.3.0 the plugin will only show the battery states for devices with a battery. I also removed the battery level and charging state characteristics. These characteristics are not supported by HomematicIP anyway.

**Comment by marcsowen** [comment]
Starting with version 0.3.0 the plugin will only show the battery states for devices with a battery. I also removed the battery level and charging state characteristics. These characteristics are not supported by HomematicIP anyway.

**Comment by mike4president** [comment]
Great update. Thanks a lot!!!

**Comment by mike4president** [comment]
my battery powered devices no longer show a battery state in the home app. :-/

**Comment by marcsowen** [comment]
I removed the battery level and charging state characteristics. You will probably only see a message when the battery is empty. I use the Flag provided by HomematicIP, whether a device is battery powered or not.

Do you use iOS version < 14?

**Comment by mike4president** [comment]
I will ry an empty battery to see if this is working. Have to find one first though. If it works this way, that's fine. No I am using 14.4. I just assumed that there is at least a battery "ok" or something like that when percentage is not reported.

**Comment by marcsowen** [comment]
@mike4president Have you tried it with an empty battery? I'm a but curious myself. Hope it works. :)

**Comment by mike4president** [comment]
Hi, I will try this weekend... sorry but work is keeping me busy. Great update 0.3.7 by the way.

**Comment by marcsowen** [comment]
Battery almost empty state was reported without any apparent issue. Closing.

**Comment by mike4president** [comment]
Sorry! Due to the lack of empty batteries I wasn't able to test this. The empty batteries I had were so empty, that no status was reported at all. I will keep an eye on this, as soon as Homematic IP reports an empty battery the next time.
