### ISSUE TITLE
Feature request: HmIP-WTH-2

### ISSUE THREAD

**Issue by mike4president** [marcsowen/homebridge-homematicip#44]
The Wandthermostat reports the temperature and the humidity. Is it possible that you chance your plugin a way that I can set up the humidity as an own device in the home app if I want?

**Comment by marcsowen** [comment]
Right now I concentrate on creating accessories which best match a HomematicIP device. Goal is to create HomeKit devices without the need of a complicated configuration file. I might support this in the future, but right now the focus is to support all possible HomematicIP devices with a sane default configuration.
