### ISSUE TITLE
Support for Node 20.0.0

### ISSUE THREAD

**Issue by marcoschmidt79** [marcsowen/homebridge-homematicip#440]
Hi, after node-update to 20.0.0 I´ve a error: 

> Mai 02 12:53:15 homebridge homebridge[28153]: TypeError: Value of "this" must be of type URLSearchParams
Mai 02 12:53:15 homebridge homebridge[28153]:     at new NodeError (node:internal/errors:399:5)
Mai 02 12:53:15 homebridge homebridge[28153]:     at Proxy.has (node:internal/url:501:13)
Mai 02 12:53:15 homebridge homebridge[28153]:     at Proxy.<anonymous> (/usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/headers.js:128:44)
Mai 02 12:53:15 homebridge homebridge[28153]:     at new Request (/usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/request.js:71:38)
Mai 02 12:53:15 homebridge homebridge[28153]:     at /usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/index.js:37:19
Mai 02 12:53:15 homebridge homebridge[28153]:     at new Promise (<anonymous>)
Mai 02 12:53:15 homebridge homebridge[28153]:     at fetch (/usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/index.js:35:9)
Mai 02 12:53:15 homebridge homebridge[28153]:     at HmIPConnector.init (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPConnector.ts:114:33)
Mai 02 12:53:15 homebridge homebridge[28153]:     at HmIPPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:140:32)
Mai 02 12:53:15 homebridge homebridge[28153]:     at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:83:14) {
Mai 02 12:53:15 homebridge homebridge[28153]:   code: 'ERR_INVALID_THIS'
Mai 02 12:53:15 homebridge homebridge[28153]: }
Mai 02 12:53:15 homebridge homebridge[28153]: TypeError: Value of "this" must be of type URLSearchParams
Mai 02 12:53:15 homebridge homebridge[28153]:     at new NodeError (node:internal/errors:399:5)
Mai 02 12:53:15 homebridge homebridge[28153]:     at Proxy.has (node:internal/url:501:13)
Mai 02 12:53:15 homebridge homebridge[28153]:     at Proxy.<anonymous> (/usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/headers.js:128:44)
Mai 02 12:53:15 homebridge homebridge[28153]:     at new Request (/usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/request.js:71:38)
Mai 02 12:53:15 homebridge homebridge[28153]:     at /usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/index.js:37:19
Mai 02 12:53:15 homebridge homebridge[28153]:     at new Promise (<anonymous>)
Mai 02 12:53:15 homebridge homebridge[28153]:     at fetch (/usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/index.js:35:9)
Mai 02 12:53:15 homebridge homebridge[28153]:     at HmIPConnector.init (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPConnector.ts:114:33)
Mai 02 12:53:15 homebridge homebridge[28153]:     at HmIPPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:140:32)
Mai 02 12:53:15 homebridge homebridge[28153]:     at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:83:14) {
Mai 02 12:53:15 homebridge homebridge[28153]:   code: 'ERR_INVALID_THIS'
Mai 02 12:53:15 homebridge homebridge[28153]: }

**Comment by marcoschmidt79** [comment]
He, I have same issue with node 20.3.0.

`
Jun 20 09:26:03 homebridge homebridge[13034]: TypeError: Value of "this" must be of type URLSearchParams
Jun 20 09:26:03 homebridge homebridge[13034]:     at new NodeError (node:internal/errors:405:5)
Jun 20 09:26:03 homebridge homebridge[13034]:     at Proxy.has (node:internal/url:511:13)
Jun 20 09:26:03 homebridge homebridge[13034]:     at Proxy.<anonymous> (/usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/headers.js:128:44)
Jun 20 09:26:03 homebridge homebridge[13034]:     at new Request (/usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/request.js:71:38)
Jun 20 09:26:03 homebridge homebridge[13034]:     at /usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/index.js:37:19
Jun 20 09:26:03 homebridge homebridge[13034]:     at new Promise (<anonymous>)
Jun 20 09:26:03 homebridge homebridge[13034]:     at fetch (/usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/index.js:35:9)
Jun 20 09:26:03 homebridge homebridge[13034]:     at HmIPConnector.init (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPConnector.ts:114:33)
Jun 20 09:26:03 homebridge homebridge[13034]:     at HmIPPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:140:32)
Jun 20 09:26:03 homebridge homebridge[13034]:     at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:83:14) {
Jun 20 09:26:03 homebridge homebridge[13034]:   code: 'ERR_INVALID_THIS'
Jun 20 09:26:03 homebridge homebridge[13034]: }
Jun 20 09:26:03 homebridge homebridge[13034]: TypeError: Value of "this" must be of type URLSearchParams
Jun 20 09:26:03 homebridge homebridge[13034]:     at new NodeError (node:internal/errors:405:5)
Jun 20 09:26:03 homebridge homebridge[13034]:     at Proxy.has (node:internal/url:511:13)
Jun 20 09:26:03 homebridge homebridge[13034]:     at Proxy.<anonymous> (/usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/headers.js:128:44)
Jun 20 09:26:03 homebridge homebridge[13034]:     at new Request (/usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/request.js:71:38)
Jun 20 09:26:03 homebridge homebridge[13034]:     at /usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/index.js:37:19
Jun 20 09:26:03 homebridge homebridge[13034]:     at new Promise (<anonymous>)
Jun 20 09:26:03 homebridge homebridge[13034]:     at fetch (/usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/index.js:35:9)
Jun 20 09:26:03 homebridge homebridge[13034]:     at HmIPConnector.init (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPConnector.ts:114:33)
Jun 20 09:26:03 homebridge homebridge[13034]:     at HmIPPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:140:32)
Jun 20 09:26:03 homebridge homebridge[13034]:     at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:83:14) {
Jun 20 09:26:03 homebridge homebridge[13034]:   code: 'ERR_INVALID_THIS'
Jun 20 09:26:03 homebridge homebridge[13034]: }
Jun 20 09:26:03 homebridge homebridge[13034]: wasm streaming compile failed: TypeError [ERR_INVALID_ARG_TYPE]: The "source" argument must be an instance of Response or an Promise resolving to Response. Received type string ('AGFzbQEBBBBBSQxgAX8AYAAB...)`

**Comment by ofri2607** [comment]
Same issue for me with node v20.9.0
No possibility to use the plugin., hombridge restarts every time after the error occurs.

**Comment by sebastian0990** [comment]
Hi, here exactly the same problem. I have performed a downgrade with the following command.
`sudo hb-service update-node 18.17.1`

Until the bug is fixed we can't use node 20. I think this bug should be fixed immediately.

**Comment by marcsowen** [comment]
I'll have a look at this next week. I'm currently on holidays.

**Comment by marcoschmidt79** [comment]
Thank you and have nice holidays. :-)

**Comment by marcsowen** [comment]
Please try version 1.2.0 (beta)
