### ISSUE TITLE
Any plans to offer this in Home Assistant?

### ISSUE THREAD

**Issue by reinisb** [marcsowen/homebridge-homematicip#446]
Hey @marcsowen ! Homebridge and your pluging is great, but as I'm adding new smart home accessories I see Homebridge's limitations and the need to move to Home Assistant. Do you have any plans on offering your plugin in Home Assistant?

**Comment by marcsowen** [comment]
Hi @reinisb , as far as I know, HomeAssistant already has a working implementation of a Homematic IP plugin: https://www.home-assistant.io/integrations/homematicip_cloud

**Comment by reinisb** [comment]
Thanks @marcsowen! Yes, I saw that Home Assistant plugin. The thing is that I'm using your Homebridge plugin to control my garage doors and it has been working really well ([the logic you have is great](https://github.com/marcsowen/homebridge-homematicip/blob/master/src/devices/HmIPGarageDoor.ts)).

With regards to Home Assistant there are move moving parts. The [HomematicIP Cloud](https://www.home-assistant.io/integrations/homematicip_cloud) plugin and its [garage door (cover) logic](https://github.com/home-assistant/core/blob/dev/homeassistant/components/homematicip_cloud/cover.py#L266) needs to work flawlessly and then also the [HomeKit Bridge integration](https://www.home-assistant.io/integrations/homekit) then needs to work flawlessly in order to be able to control my garage doors. A lot of moving parts. I suppose the only way to know if that will work is to try it out :)

**Comment by reinisb** [comment]
A short update. I set up Home Assistant as well as the [HomematicIP Cloud](https://www.home-assistant.io/integrations/homematicip_cloud) plugin and HomeKit Bridge addon.

It is possible to open and close the HomematicIP garage door, however unfortunately neither in Home Assistant, nor in Homekit the state "Opening" and "Closing" have been implemented. For example, if garage doors are closed, then when I press "Open", then the Garage door remains in status "Closed" for 30 seconds and will change status to "Open" only when the new garage door position is fully "Open". The same happens inverse with "Closing".

In your Homebridge addon you support all possible states "Open", "Closed", "Opening", "Closing" which is fantastic. I guess your logic is defined [here](https://github.com/marcsowen/homebridge-homematicip/blob/master/src/devices/HmIPGarageDoor.ts#L169C1-L184C4). However, in Home assistant it looks like their logic [here](https://github.com/home-assistant/core/blob/dev/homeassistant/components/homematicip_cloud/cover.py#L266-L297) does not have the logic to set "Opening" and "Closing" (even though the Cover component that Home Assistant uses does support such states).

**Comment by reinisb** [comment]
@SukramJ tagging you for visibility, perhaps there's an easy way to extend [the logic](https://github.com/home-assistant/core/blob/dev/homeassistant/components/homematicip_cloud/cover.py#L266-L297) to support "Opening" and "Closing" states like [here](https://github.com/marcsowen/homebridge-homematicip/blob/master/src/devices/HmIPGarageDoor.ts#L169C1-L184C4).

**Comment by SukramJ** [comment]
@reinisb Please don't tag me!

Check the [the HA dev docs](https://developers.home-assistant.io/docs/core/entity/cover).
If you change the change it, you need a discussion [here](https://github.com/home-assistant/architecture).
