### ISSUE TITLE
FetchError: request to https://lookup.homematic.com:48335/getHost failed, reason: connect ECONNREFUSED 62.113.249.71:48335

### ISSUE THREAD

**Issue by marcoschmidt79** [marcsowen/homebridge-homematicip#448]
FetchError: request to https://lookup.homematic.com:48335/getHost failed, reason: connect ECONNREFUSED 62.113.249.71:48335
Nov 02 17:41:11 homebridge homebridge[8120]:     at ClientRequest.<anonymous> (file:///usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/index.js:108:11)
Nov 02 17:41:11 homebridge homebridge[8120]:     at ClientRequest.emit (node:events:526:35)
Nov 02 17:41:11 homebridge homebridge[8120]:     at TLSSocket.socketErrorListener (node:_http_client:495:9)
Nov 02 17:41:11 homebridge homebridge[8120]:     at TLSSocket.emit (node:events:514:28)
Nov 02 17:41:11 homebridge homebridge[8120]:     at emitErrorNT (node:internal/streams/destroy:151:8)
Nov 02 17:41:11 homebridge homebridge[8120]:     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
Nov 02 17:41:11 homebridge homebridge[8120]:     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
Nov 02 17:41:11 homebridge homebridge[8120]:   type: 'system',
Nov 02 17:41:11 homebridge homebridge[8120]:   errno: 'ECONNREFUSED',
Nov 02 17:41:11 homebridge homebridge[8120]:   code: 'ECONNREFUSED',
Nov 02 17:41:11 homebridge homebridge[8120]:   erroredSysCall: 'connect'
Nov 02 17:41:11 homebridge homebridge[8120]: }
Nov 02 17:41:11 homebridge homebridge[8120]: FetchError: request to https://lookup.homematic.com:48335/getHost failed, reason: connect ECONNREFUSED 62.113.249.71:48335
Nov 02 17:41:11 homebridge homebridge[8120]:     at ClientRequest.<anonymous> (file:///usr/local/lib/node_modules/homebridge-homematicip/node_modules/node-fetch/src/index.js:108:11)
Nov 02 17:41:11 homebridge homebridge[8120]:     at ClientRequest.emit (node:events:526:35)
Nov 02 17:41:11 homebridge homebridge[8120]:     at TLSSocket.socketErrorListener (node:_http_client:495:9)
Nov 02 17:41:11 homebridge homebridge[8120]:     at TLSSocket.emit (node:events:514:28)
Nov 02 17:41:11 homebridge homebridge[8120]:     at emitErrorNT (node:internal/streams/destroy:151:8)
Nov 02 17:41:11 homebridge homebridge[8120]:     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
Nov 02 17:41:11 homebridge homebridge[8120]:     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
Nov 02 17:41:11 homebridge homebridge[8120]:   type: 'system',
Nov 02 17:41:11 homebridge homebridge[8120]:   errno: 'ECONNREFUSED',
Nov 02 17:41:11 homebridge homebridge[8120]:   code: 'ECONNREFUSED',
Nov 02 17:41:11 homebridge homebridge[8120]:   erroredSysCall: 'connect'
Nov 02 17:41:11 homebridge homebridge[8120]: }

**Comment by marcoschmidt79** [comment]
After rebrot and Node 21 works fine.

**Comment by eiSi2010** [comment]
Hi, habe das gleiche Problem. Allerdings bringt ein Update von Node.js bei mir leider nichts (er bietet mir auch maximal v. 20.14 an)
