### ISSUE TITLE
Implementation of HmIP-FSI16

### ISSUE THREAD

**Issue by sommer-nt** [marcsowen/homebridge-homematicip#449]
Hello @marcsowen, 

Would it be possible to integrate the **HmIP-FSI16** in your next release?
I would be very pleased to be able to control these actuators via HomeKit.

Thanks in advance.

BR
Daniel

**Comment by marcsowen** [comment]
Hi @sommer-nt . The device has been implemented since version 1.3.1. Please give it a try.

**Comment by sommer-nt** [comment]
Great, thank you very much.
I have now tested it for a week. It works very well.
