### ISSUE TITLE
Using Homekit alarm

### ISSUE THREAD

**Issue by mike4president** [marcsowen/homebridge-homematicip#45]
Hi, as fas as I know the homematicip-rest-api also reports the alarm setting of the access point. Is it possible that you make this device also available in you plugin? In Home Assistant this device is reported an I can set it up in homekit.

**Comment by marcsowen** [comment]
Yes, that's the plan. See issue #22

**Comment by marcsowen** [comment]
Starting with version 0.3.0 the plugin supports a "Home Security System" device which controls the HomematicIP security systems including internal and external alarms.

**Comment by mike4president** [comment]
I didn't expect this feature to arrive that soon. Thanks for your time and effort. I'll leave this issue open until I can report it as stable... I will test it the coming days..

**Comment by marcsowen** [comment]
@mike4president How's the testing going? Are there any issues?

**Comment by marcsowen** [comment]
The geo based automation is completely in Apples hands. One thing to keep in mind: The activation of the alarm system takes around 30 seconds. This is a feature (or limitation) of the HomematicIP cloud.

**Comment by mike4president** [comment]
okay, the past days it has been working flawlessly. Thanks.
