### ISSUE TITLE
weather data of access-point as homekit device

### ISSUE THREAD

**Issue by mike4president** [marcsowen/homebridge-homematicip#47]
As far as I know the homematicip-rest-api also reports the weather data of the access point. Is it possible you make this weather data available as a homkit device so I can use it for automations?

**Comment by marcsowen** [comment]
I hesitate a bit on doing that. I believe eq-3 is paying license fees to some kind of weather service. You might argue that you paid for it by buying all those HomematicIP devices. But I don't think the license covers for a third party plugin to "just" use the data for something which was not intended by neither companies. I might check back on eq-3 if they are ok with that.

In meantime, you might wanna check out a dedicated homebridge plugin like: https://github.com/naofireblade/homebridge-weather-plus
