### ISSUE TITLE
Unable to generate Auth_Token

### ISSUE THREAD

**Issue by Adlermk23** [marcsowen/homebridge-homematicip#479]
Moin, Thank you for providing such a helpful tool. Unfortunately I was unable to pair my AccessPoint 
Pressing the button docent result in a Token being put out.

> [HomematicIP] Initializing HomematicIP platform...
> [11/12/2023, 10:40:09] [HomematicIP] homebridge-homematicip v1.2.0
> Setup Payload:
> X-HM://0023N5HVUZ8T1
> Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
>                        
>     ┌────────────┐     
>     │ 104-48-074 │     
>     └────────────┘     
>                        
> [11/12/2023, 10:40:10] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge 9619) is running on port 51030.
> [11/12/2023, 10:40:10] [HomematicIP] Press blue, glowing link button of HmIP Access Point now!
> [11/12/2023, 10:40:15] [HomematicIP] Press blue, glowing link button of HmIP Access Point now!
> [11/12/2023, 10:40:20] [HomematicIP] Press blue, glowing link button of HmIP Access Point now!

> ...

Is there any solution to this issue? 

Thanks in advance!

Update: I just discovered that there's a new user-management. in the Homematic App. Basically a System-Pin doesn't exist anymore, but you need setup an Admin user with a Admin-PIN.

![IMG_32D91EDC9C6A-1](https://github.com/marcsowen/homebridge-homematicip/assets/153501578/388b467d-9255-487a-b621-e00fad11f575)

**Comment by fuzzyly** [comment]
I am facing the same problem. Is there a solution yet?

**Comment by fuzzyly** [comment]
If you're doing it right, then it works. 
1 Configuring plugin with the SGTIN (leaving AUTH_TOKEN empty) save & restart
2 opening logs and push the button on the access point when prompted, copy AUTH_TOKEN given in the logs. 
3 insert it in configuration AUTH_TOKEN and restart: everything is visible in HomeKit

In the Homematic app a new user homebridge-homematicip with restricted access is also visible. 

Thank you for doing this plugin!

**Comment by Adlermk23** [comment]
I still can't get it to work. just tried it again with the latest version of the plugin.

I tried following your instructions step by step. same result. "Press blue, glowing link button of HmIP Access Point now!" but pressing it doesn't generate a Token in the log

**Comment by marcsowen** [comment]
Most likely you mistyped the access point id. The config should be like:

"access_point": "36644affe8332d234234",

If you set a PIN, also provide the PIN for the pairing to work:

"pin": "1234"

Did you set up "user rights" in the Homematic IP app? I haven't done so yet, so it might be, that the plugin doesn't work when using "user rights". Maybe someone else testet it already?

**Comment by Adlermk23** [comment]
Thanks, still didn't work.

Yes I think it is because of the "user rights" basically there isn't a general system pin anymore. now there are others with a pin. and it seems like you can't go back to the old system once you activated it. So at the moment it seems like there is no solution

**Comment by marcsowen** [comment]
I'm hesitating to switch to user rights, since if I can't get it to work, I can't use the plug-in anymore. Also I cannot support people on the old system anymore - if it does work. I might switch over eventually, but not at the moment.

Maybe somebody else can provide support and/or patches?

**Comment by fuzzyly** [comment]
I only have one user but with user rights defined and no problem with generating the code by pushing the glowing blue button.

**Comment by Adlermk23** [comment]
I Finally got it working. It seems like I had a hardware problem with one of my APs. The button didn't work! I use 2 APs and after I tried everything else I swapped them. 

So good news @marcsowen: user rights doesn't seem to be an issue.
