### ISSUE TITLE
node update to 20.11 let plugin stop working

### ISSUE THREAD

**Issue by Teschbert** [marcsowen/homebridge-homematicip#502]
today I updated node.js on my homebridge (Raspi4b) to the newest release 20.11.0
When restarting homebridge the homematicip plugin comes up with errors:

[HomematicIP] Cannot lookup device: request={"clientCharacteristics":{"apiVersion":"10","applicationIdentifier":"homebridge-homematicip","applicationVersion":"1.2.0","deviceManufacturer":"none","deviceType":"Computer","language":"de_DE","osType":"Linux","osVersion":"6.1.21-v8+"},"id":"3014F711A00003D3C9952C31"}, headers={"Content-Type":"application/json","Accept":"application/json","VERSION":"12","AUTHTOKEN":"","CLIENTAUTH":"EB04B98F55B050A68E51783CFC7D811808AEF1CB4D2CBEDA48F2EF172CAF5536412AE6C79282F3D0F11565B08164407EB4BA139FBE2EEF3A677D2675D98F550C"}, code=418, message=, json={"errorCode":"INVALID_REQUEST"}

After downgrading to node 20.10.0 everything was fine again.

Could you please check?

**Comment by marcsowen** [comment]
Hi @Teschbert - I don't think it's a problem with node. Sometimes I get the same error and after restart this error is gone. Sometimes eq3 doesn't like the request. I don't know why.

**Comment by Teschbert** [comment]
ok. Then I'll update node again tomorrow and test - maybe doing a second restart of homebridge.
Do you run node 20.11.0 or an earlier version?

**Comment by marcsowen** [comment]
Personally I run node v20.11.0 on my machine, yes. Seems to work.

**Comment by Teschbert** [comment]
Did a quick update to 20.11 and your Plugin to 1.3.1, restart .... working!
Very strange ...
But ok. Thanx for your Inputs!
