### ISSUE TITLE
Fehler beim Starten des Plugins.

### ISSUE THREAD

**Issue by hotdotdev** [marcsowen/homebridge-homematicip#6]
Es scheint ein Fehler beim Plugin zu geben. Folgendes gibt mir das Log aus, der Homebridge-Server startet dadurch nicht:

![FD4BBB74-6472-4DFD-9FDC-8DB00ED81BFD](https://user-images.githubusercontent.com/8043541/104438701-95b12c00-5590-11eb-9d73-98a0aa692dce.jpeg)
![CFE72A2F-15FD-484A-9D2A-24FC39193321](https://user-images.githubusercontent.com/8043541/104438713-98ac1c80-5590-11eb-9374-1bd26a72bea3.jpeg)

**Comment by nsowen** [comment]
@hotdotdev Danke für den Hinweis! Die node-fetch gelistete Version scheint aus NPM verschwunden. Schau mal, ob es mit v0.0.3 nun auch bei dir funktioiert.

**Comment by hotdotdev** [comment]
@nsowen Danke für den schnellen Fix, hat leider nicht geholfen. Fehlerbild mit 0.0.3 ist gleich.

**Comment by marcsowen** [comment]
@hotdotdev Sorry, node-dev war nicht als Requirement eingetragen. Ist mit 0.0.4 gefixed.
