### ISSUE TITLE
since Update to 0.3 duplicated sensors

### ISSUE THREAD

**Issue by knipsa** [marcsowen/homebridge-homematicip#60]
hello, since I updated to v.0.3 I got duplicated sensors coming within the alarm system. Both window sensors are now shown twice, one of them will send alerts of open/close windows, the other one is shown as window. So if I choose a room with one window/magnet sensor, HomeKit shows 2 windows. Downgrade to v.0.25 didn‘t help. The security system is great, but if the double sensors is a side effect, we need a fix for that. Thank you 
![266AAD0D-C0F0-4A38-BBFB-9B4F9C03F4EA](https://user-images.githubusercontent.com/79795858/109420970-a51bf580-79d5-11eb-95b0-f13fa92f9f5c.jpeg)
![FBD06273-3489-4459-B1AF-BB48B109D4AF](https://user-images.githubusercontent.com/79795858/109420972-a816e600-79d5-11eb-95e0-111767ae7607.jpeg)
![035F3217-FB0A-4748-8891-52C80F98ED8F](https://user-images.githubusercontent.com/79795858/109420973-a816e600-79d5-11eb-833e-fdf619f8e099.jpeg)

**Comment by marcsowen** [comment]
Hmm... apparently the two services (contact sensor and window service) of one accessory are split up as two devices in the Home App. So we could do two things:

- Use only either contact sensor (without "tilted" option) or window service (with window state of either 0, 50 or 100%)
- Make it a configurable option (global/per device?)

**Comment by knipsa** [comment]
thanks for your fast reply...I think it would be great to make it configurable...before v0.3 everything works fine, now it’s a bit confusing...you are doing a great job, man! Thank you

**Comment by mike4president** [comment]
I am having the same issue with HmIP-SWDO-I window sensor. I already cleared the homebridge device cache which did not help. I'd prefer to only use the contact sensor or to make it a configurable feature since I can declare a contact sensors as a windows sensor in the home app.

**Comment by knipsa** [comment]
It is possible that the new alarm messages of the door / window sensors can be also configured in such a way that they only send push notifications (open / closed) if the alarm system is activated (absent = true). When I'm at home and the alarm is off, I don't want to receive a push message every time the balcony door is opened / closed. when the alarm system is on, things look different, of course.

**Comment by marcsowen** [comment]
That has nothing to do with the alarm system. You get a push message because at least one of the sensors (I know, you have two sensors now for each contact sensor, I'll fix that) is configured to send status updates. Go to:

- Your contact sensor device
- Click on Accessories (2) (German: "Geräte")
- Check each accessory:
- Status and Notifications (German: "Status und Mitteilungen")
- Disable "Notifications on this iPhone" (German: "Mitteilungen auf diesem iPhone")

If you have done it before, remember that you have a second device now for the same window. So your second device might send the notifications while the first one is quiet.

**Comment by knipsa** [comment]
ok, sorry my English is to bad. I try again: 
The Balcony Door has no Setting for Notifications. The Contact Sensor has disabled notifications, but I get a push notification with each status change. It would be nice, if the alarm messages of the status changes of the sensors only will be pushed, when the alarm system is activated. 
![45271E2A-18C0-473F-A2C2-C495F53DAEE7](https://user-images.githubusercontent.com/79795858/109466860-a8ad8c00-7a6a-11eb-9c35-abfe4b3dad1f.png)
![Uploading FB473031-CF9C-48B3-A88D-1ABCBA58AB55.png…]()

**Comment by knipsa** [comment]
![0C520310-08E6-4FBF-84D5-BC03665D5D35](https://user-images.githubusercontent.com/79795858/109466956-cbd83b80-7a6a-11eb-9f9d-88e1feeacb15.png)

**Comment by marcsowen** [comment]
Click on "Geräte 2 >" just below "Raum Wohnzimmer. You will see two devices behind "Geräte 2 >". Maybe only one of them has notifications disabled and the other (new) one has it activated.

**Comment by knipsa** [comment]
ok i got. Didn’t know that there are Different Options recording to the enter Point of the Sensor. If I select it your way, notifications where enabled for the sensor. I disabled it..thank you and sorry

**Comment by marcsowen** [comment]
Yes, it's very confusing right now. I'll fix that soon.

**Comment by marcsowen** [comment]
Sorry for the delay, but I just updated the plugin to version 0.3.1. This should remove the second service from all contact and rotary handle sensors.

**Comment by knipsa** [comment]
Great, now I have no duplicated sensors. Thank you!

**Comment by mike4president** [comment]
Great update. Thanks!!! Solved my problem
