### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by toni-Berg** [marcsowen/homebridge-homematicip#7]
Homebridge 1.1.7
PlugIn Version 0.0.4

Hello. I have a new problem. 
Sign in now works. 
Status = OK. 
Then comes this message:

------------

(node:1218) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'oem' of undefined
    at HmIPPlatform.setHome (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:182:13)
    at HmIPPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:112:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1218) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1218) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

-----------------
No devices are displayed. A restart does not improve.

**Comment by marcsowen** [comment]
Apparently the API call to the endpoint home/getCurrentState does not succeed. There is a missing try/catch block which should handle the error more gracefully. I will need to implement more debugging logs to see what's going on. Are you sure the correct access point and token has been supplied in the config?

**Comment by toni-Berg** [comment]
Homebridge 1.1.7
PlugIn Version 0.0.4
RPI Homebridge Image

Hello marcsowen, I tested it on 2 different Homebridge with the same AccessPoint installations. 
Unfortunately, always the same result. 
In IoBroker, sign-in works. This is also displayed in the HomeMaticIP-App as a separate user. This is not currently done. 
Even restarting again has not brought any improvement.

----
[13/01/2021, 20:23:16] ---
[13/01/2021, 20:23:16] Loading 3 platforms...
[13/01/2021, 20:23:16] [Config] Initializing config platform...
[13/01/2021, 20:23:16] [Config] Running in Service Mode
[13/01/2021, 20:23:16] [Homebridge Kiwigrid] Initializing Homebridge Kiwigrid platform...
[13/01/2021, 20:23:16] [HomematicIP] Initializing HomematicIP platform...
Setup Payload:
X-HM://0024NU9RZLI3I

[13/01/2021, 20:23:16] Homebridge is running on port 51612.
(node:1054) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'oem' of undefined
    at HmIPPlatform.setHome (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:182:13)
    at HmIPPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-homematicip/src/HmIPPlatform.ts:112:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1054) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1054) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by toni-Berg** [comment]
Hello marcsowen, Thank you for your help. I was able to narrow down the error. My AccessPoint is not responding correctly and does not return the auth token. It worked with another AccessPoint. The device appears to be faulty. However, I was able to log in with the Auth token from the IoBroker. Thank you for your work. Please also implement the hmIP-BBL and HmIP-BROLL devices.
