### ISSUE TITLE
Try to insert 2 HMIP-Access Points into Plugin

### ISSUE THREAD

**Issue by olina2911** [marcsowen/homebridge-homematicip#71]
Hi Marc,

I try to insert 2 HMIP-AP into the Plugin, but that doesen't work. Is there any workaround to do this?

**Comment by marcsowen** [comment]
You only need to add one access point. But I'm currently also a bit puzzled on which one. I believe one is actually the "main" access point. Can you try either one? (Maybe the first one shown in the "updates" section of the HomematicIP app.)

**Comment by olina2911** [comment]
Sorry my English is not really good...hope you can follow me anyway... :-)
No I don't use advanced routing, because my apps are only wifi AP's, they don't support advanced routing.

Two instances...yes I tried it like this

{
            "platform": "HomematicIP",
            "name": "Wohnzimmer",
            "access_point": "3014-F711-A000-215B-E99C-XXXX",
            "auth_token": "XXX"
        },
        {
            "platform": "HomematicIP",
            "name": "Garage",
            "access_point": "3014-F711-A000-215B-E999-YYY",
            "auth_token": "YYY"
        },

**Comment by marcsowen** [comment]
Hi. Sorry for the late reply. Now I understand your problem. I wasn't aware that the WiFi versions of the HomematicIP access points don't support Advanced Routing. So you have both access points paired with your HomematicIP app? Do you have one or two "homes" within the app? Do you need to switch homes ("Multi Home-Verwaltung") when controlling a device in the garage?

If you have only one home, there could be a conflict with the "Home Security System" device, which can only exist once per HomematicIP home. It could also be any other accessory (device) which still might be cached within homebridge. Have you tried to delete the homebridge cache? Depending on your installation it's located unter /var/lib/homebridge/persist and /var/lib/homebridge/accessories.

**Comment by olina2911** [comment]
Hi Marc, no problem. You are totally right, I have two „homes“ configured.
In homematic app I have to switch to Garage.

**Comment by marcsowen** [comment]
```
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 99811ccc-c6e9-4ec2-b495-8e32a722f268
at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/.......
```

Do you have by any chance more error lines in the logs?

**Comment by olina2911** [comment]
Sure, I will rebuild it and poste it here

**Comment by olina2911** [comment]
That´s my actual config:
{
            "platform": "HomematicIP",
            "name": "Wohnzimmer",
            "access_point": "3014-F711-A000-215B-E99C-XXXX",
            "auth_token": ""
        },
        {
            "platform": "HomematicIP",
            "name": "Garage",
            "access_point": "3014-F711-A000-215B-E999-YYYY",
            "auth_token": ""
        },

The error logs have changed:
"
The dynamic platform HomematicIP from the plugin homebridge-homematicip seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!"

"[15/03/2021, 08:53:00] [homebridge-homematicip] Could not restore cached accessory 'WZT1': Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 99811ccc-c6e9-4ec2-b495-8e32a722f268"

Accessory WZT1 ist parier with the "Wohnzimmer" Bridge

**Comment by olina2911** [comment]
Hi Marc now both AP work. I reinstalled the Plugin und what should i say... both AP‘s are reachable

thanks for your time and support 
Greatings from germany

**Comment by marcsowen** [comment]
Perfect! :) I guess one device was still in the cache for the wrong access point. I don't know why, but I'm happy it works now.

You still get this message, right?

> The dynamic platform HomematicIP from the plugin homebridge-homematicip seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!

**Comment by olina2911** [comment]
Yes this message is still in log...
What does this message mean?

**Comment by marcsowen** [comment]
It just means we need to think about a new solution soon. I guess homebridge wants us to configure the platform "homematicip" just once and use two different access points configuration inside this single configuration, like:

```
{
    "platform": "HomematicIP",
    "name": "My HomematicIP home",
    "access_points": [
        {
            "access_point": "3014-F711-A000-215B-E99C-XXXX",
            "auth_token": "",
            "name": "Wohnzimmer"
        },
        {
            "access_point": "3014-F711-A000-215B-E999-YYYY",
            "auth_token": "",
            "name": "Garage"
        }
    ]
}
```

But this is not supported (yet).
