### ISSUE TITLE
Please add HmIP-BDT

### ISSUE THREAD

**Issue by Ponanski** [marcsowen/homebridge-homematicip#78]
Can you add HmIP-BDT please?  Our rooms are all equipped with these actuators.  Otherwise everything works perfectly, even the alarm.  

thank you very much for your excellent work!

**Comment by marcsowen** [comment]
Sure. I don't habe those actors, so you need to help me a bit. By looking at the API I ask myself whether you can turn on the switch on and off without setting a dim level? When you switch it on will it return to the last dim level set before turning it off? Or will it always switch to 100%? Or can't you just turn it on and you will always need to set a dim level (with a slider)?

What about the actor itself? Do you need to press and hold when turning it on, or do you press shortly on the button and it turns on to the last dim level set before turning it off?

Thanks!

**Comment by Ponanski** [comment]
The HmIP-BDT is pressed briefly once and always switches on 100%.  If I hold the button down for a long time, it is dimmed.
![A0C384F3-987F-4A63-873F-D339EDC88ECF](https://user-images.githubusercontent.com/81046344/111903573-3ca7bd80-8a43-11eb-8075-07a61452ae0e.png)

**Comment by marcsowen** [comment]
Ok, that's much simpler than I thought. I will keep you up to date.

**Comment by marcsowen** [comment]
Try version 0.4.1. I added the dimmer devices but couldn't test it yet. I bought one myself to play around with but it won't arrive until Tuesday. HomeKit has two states to keep track of the dimmer: ON/OFF and brightness. HomematicIP seems to only track the brightness. I tried to emulate the ON/OFF state by setting the brightness to 0% (OFF) and 100% (ON). I hope this has the desired effect.

Please let me know if something doesn't work right.

**Comment by Ponanski** [comment]
The first thing I can say is that the dimming value is wrong.  It's actually 40% and HomeKit shows 60%.

**Comment by Ponanski** [comment]
What I noticed now is that if you change the dimming value, the light goes to 100% and then adjusts the set value from there, which is noticeable by a brief flash

**Comment by marcsowen** [comment]
Do you get the flash when the light is off and you set a dimming level? HomeKit might switch on the light first (set it to 100%) and then set it to the desired dimming level. But then it shouldn't flash when changing from and dimmed on state to a different dimming level.

I will optimize that when my dimmer arrives.

**Comment by Ponanski** [comment]
I don't know how to describe it better.  "Flashing" is wrong but unfortunately my English is not the best and I am currently working with a translator ... you will see for yourself when you have your actor.  It's not bad, but it's noticeable.  But otherwise everything works as it should be until now

**Comment by marcsowen** [comment]
Ok, I'll check when I have the actor. I'll keep you informed.

**Comment by Ponanski** [comment]
I would like to inform you that the HmIP-BDT has worked very well and reliably so far, apart from the "problem" with dimming.  I use this every day with the home app and as a voice command.

**Comment by marcsowen** [comment]
Great to hear that. My dimmer just arrived and I fixed the flashing issue. Try version 0.4.2 - it should be much better.

There seems to be a difference between the Home app and the Eve app. While the Home app sends a brightness command right after the "on" command, the Eve app doesn't.  That's why in the Eve app the dimmer won't turn on when just flipping the on switch. It will stay off since the brightness is set to 0. You will need to move the slide afterwards or just use the slider without flipping the switch.

Anyway, it seems to work great in the Home app.

**Comment by nsowen** [comment]
Guten Tag und vielen Dank für Ihre Nachricht!

Ich befinde mich aktuell in Elternzeit und bin ab dem 6. April 2021 wieder für Sie erreichbar. Bitte wenden Sie sich an Dirk Vleugels (dvl (at) 2scale.net).

Viele Grüße,

Nils Sowen

**Comment by marcsowen** [comment]
Ok, I fixed the Siri issue with 0.4.3. The drawback is that you will get a short flash when sliding from 0% to some dimming value. The light will shortly "switch on" to 100% and then dim to the desired value. When moving from any other dimming level to some other value, everything works fine.

**Comment by Ponanski** [comment]
Thank you! The problem with dimming has been solved and now works absolutely flawlessly!

Is it known why the voice command "Hey Siri, lights on" no longer works? Can this still be changed or is that the compromise that it works now?

**Comment by Ponanski** [comment]
Excellent! Thanks to you, I can finally control my entire system with almost 60 devices via Siri. The voice command works again and I don't have "Flash", everything works as it should. Just great!

The problem is solved for me. You are really doing a great job and I love your plugin!

Thank you very much!

**Comment by marcsowen** [comment]
Thank you for the kind feedback! If something is missing, let me know.
