### ISSUE TITLE
piVCCU setup

### ISSUE THREAD

**Issue by maschbaer** [marcsowen/homebridge-homematicip#99]
Hello,

I would like to use the plugin with my piVCCU. However, I do not have:
- access point ID
- API auth token
- PIN if set in the app

On Homeassistant I asses the piVCCU just via the IP adress/Pirt and user/PW.

Could you please explain how to setup the plugin for piVCCU.

regards
Jan

**Comment by marcsowen** [comment]
Hi @maschbaer ,

I'm not familiar with piVCCU but as far as I understood this software runs the original CCU software thus emulating an original CCU2 system. My plugin can only be used with the original HomematicIP access point ("HmIP-AP"). Well indirectly. It actually connects to the HomematicIP cloud used by this type of access point.

When using the HomematicIP access point, the access point ID is printed on the access point itself. The PIN is optionally set in the complementary HomematicIP app (on iOS/Android). The API auth token can then be generated with the plugin itself.

**Comment by maschbaer** [comment]
Ok understood.
